### ISSUE TITLE
Gametimer the other way around

### ISSUE THREAD

**Issue by Fransje** [inexor-game/code#103]
Make the gametimer count up instead of down. Easier and more intuitive for mathematically lacking people like me when timing items in ffa and jumping through a demo.

**Comment by a-teammate** [comment]
Imo this should be optional, bc e.g. for me it would be less intuative, as im not really playing that much ffa.

But i guess it could be very easily just a simple modification of the hud/scoreboard website

Demos.. hm.. :D this is another part where generally some more modifications will be necessary

**Comment by Croydon** [comment]
To be honest I don't see a need for that as a default feature. However modding the timer shouldn't be a big problem with the new UI's :)

**Comment by Croydon** [comment]
Our position for the moment is, that we aren't going to do that. However, if somebody needs it, it will be probably easy enough to modify the timer with a custom script.
