### ISSUE TITLE
Protoc fails to be found on Ubuntu

### ISSUE THREAD

**Issue by koraa** [inexor-game/code#123]
@Calinou Please provide more info on this.

**Comment by Calinou** [comment]
Setting the path of protoc by hand (which is `/usr/bin/protoc)` works.

**Comment by koraa** [comment]
@Calinou Could you please try again without setting protoc manually and post the error, out and cache files that cmake generates and the build logs?

**Comment by Calinou** [comment]
I've switched to Debian testing recently, so it might vary a bit. Anyway, this error still happens.

CMakeCache.txt: http://paste.ubuntu.com/10640629/
CMakeOutput.log: http://paste.ubuntu.com/10640632/

**Comment by koraa** [comment]
Hmm. Those logs don't say much. Is there an error log? Could you post the console output?

Where are the headers/libs actually located?
