### ISSUE TITLE
CMake error on enet

### ISSUE THREAD

**Issue by Calinou** [inexor-game/code#125]
Local enet is used, despite me having installed the `libenet-dev` package. CMake GUI is used, operating system is Debian 8 (jessie/testing) 64-bit.

```
CMake Error at src/CMakeLists.txt:77 (add_subdirectory):
  The source directory

    /home/calinou/Git/inexor/src/libraries/enet

  does not contain a CMakeLists.txt file.
```

**Comment by koraa** [comment]
Please post the following files from your build directory: CMakeCache.txt, CMakeOutput.log and CMakeError.log

**Comment by koraa** [comment]
And the visible build log itself (the one printed on the console) would be useful too :)

**Comment by Calinou** [comment]
CMakeOutput.log: http://paste.ubuntu.com/10641686/
CMakeCache.txt: http://paste.ubuntu.com/10641688/

**Comment by koraa** [comment]
The distribution's enet is not use.
Instead we compile our own.

Did you initialize the submodules?

**Comment by Calinou** [comment]
Right, I again forgot to do it. Sorry.
