### ISSUE TITLE
odd crosshair code in rendergl.cpp

### ISSUE THREAD

**Issue by IAmNotHanni** [inexor-game/code#129]
I found some strange code passages:

``` c++
#define MAXCROSSHAIRS 4
/// Dynamic arrays / vectors are much better than conditional compiling!
/// Why do we limit ourselves here?? I don't like the initialisation.
static Texture *crosshairs[MAXCROSSHAIRS] = { NULL, NULL, NULL, NULL };

/// why not use int *i ?
/// So we do not need loadcrosshair_ anymore
void loadcrosshair(const char *name, int i)
{
    if(i < 0 || i >= MAXCROSSHAIRS) return;
    crosshairs[i] = name ? textureload(name, 3, true) : notexture;
    if(crosshairs[i] == notexture) 
    {
        name = game::defaultcrosshair(i);
        crosshairs[i] = textureload(name, 3, true);
    }
}
/// Looks like someone wrote a hook. 
/// loadcrosshair is called anyway
void loadcrosshair_(const char *name, int *i)
{
    loadcrosshair(name, *i);
}
COMMANDN(loadcrosshair, loadcrosshair_, "si");
```

**Comment by koraa** [comment]
What's odd about then? And what should we do about it?

**Comment by IAmNotHanni** [comment]
* we don't need the function loadcrosshair_ at all. 
 * Looks like Sauerbraten limits itself to 4 crosshairs: normal crosshair, teammate icon crosshair, hit crosshair (and one more?). But there is no reason to do so. Is there anything against using std::vector instead?

**Comment by koraa** [comment]
sounds great.
go ahead!

**Comment by Croydon** [comment]
The crosshairdir var isn't even getting used there? Also even when it would be there it should become a relative path to the interfacedir (var). @a-teammate did not finish this yet :)

**Comment by IAmNotHanni** [comment]
ok

**Comment by Croydon** [comment]
Paths will be fixed with #134.

**Comment by Croydon** [comment]
8820b91aebbb8e3deeeecc3526ad1e162bdca5b6

**Comment by Croydon** [comment]
Talked to @IAmNotHanni. This bug got a WONTFIX due to more heavy upcoming refactoring.
