### ISSUE TITLE
Windows server isn't startable because icon is missing

### ISSUE THREAD

**Issue by koraa** [inexor-game/code#133]
There was a conversation on the 0.1a pad about the server not being startable on windows.
Does this still apply?

> make the server startable on windows, by fixing the missing icon thing, maybe refactoring that by using the SDL2 function (https://stackoverflow.com/questions/19311609/how-do-i-set-window-titlebar-icon-and-alt-tab-icon-in-sdl2-c-visual-studio)
>
> just remove the icon-adding part as long as we dont have one
>
> we have a working one
>
> as long as its not the final state it shouldnt be included
>
> others may feel encouraged to create an own icon thehhhhhhhhhhhhhhh

**Comment by Croydon** [comment]
Yes.

**Comment by koraa** [comment]
Can you fix it?

**Comment by Croydon** [comment]
I can't change it to use the SDL functions, which might be a better solution from what I understand. But I could try to simple add the missing files. 
What logo should I use for that temporarily?

**Comment by a-teammate** [comment]
fixed with a9d35c1ec4df608b9efd7c432d277dd286b917ff
