### ISSUE TITLE
Detection of unused resources

### ISSUE THREAD

**Issue by aschaeffer** [inexor-game/code#145]
Once we have finished the refactoring of the media/resource management (JSON, maps, textures, models, ...) we can implement an auto detection mechanism for unused resources (like "apt-get autoremove" in debian). Also we can count how often a resource is used (popular textures / models) which could be useful in the edit UI.

**Comment by Croydon** [comment]
Even we only provide a minimalist package of default content, it can happen that we don't use every texture of a texture pack, but still delivering it, to offer some choice to map builders, who don't have anything, but our default package.

To sum it up, I'm not sure how helpful this is, but as long as nobody just remove anything, which don't get used, it should be okay.

**Comment by aschaeffer** [comment]
Agree.

**Comment by MartinMuzatko** [comment]
Considering last/most used content in the ui is a great aspect to consider.  Last servers, textures, maps. Etc..

**Comment by Croydon** [comment]
@MartinMuzatko I guess you are talking about how often something is actually getting played, but this issue is about how often textures, models and other resources are actually included in local maps.
