### ISSUE TITLE
Do not save getmaps to harddisk

### ISSUE THREAD

**Issue by a-teammate** [inexor-game/code#148]
This is an implementation detail. 
Currently getmaps creates a file on the harddisk, loading it from the harddisk, followed by deleting it again.
This could be simplified by loading directly from the memory.

**Comment by a-teammate** [comment]
Mark as wontfix since we need to move away from distributing our maps and content in C++ but instead handle that in nodejs

**Comment by Croydon** [comment]
And if we distribute not only maps but also textures and stuff it's reasonable to save it to disk.
