### ISSUE TITLE
“Pogo stick” option

### ISSUE THREAD

**Issue by Calinou** [inexor-game/code#153]
I suggest adding a “pogo stick” option, which lets you continue jumping without having to press the Jump key every time. Instead, you just have to hold the Jump key, like in Xonotic and Warsow.

It could probably be enabled by default.

**Comment by Croydon** [comment]
What's the purpose of that?

**Comment by Calinou** [comment]
Well, avoiding RSI (Repetitive Strain Injury) which is caused by pressing the same key a lot of times for no reason.

It's already possible to mod Sauerbraten and Tesseract to add that.

**Comment by a-teammate** [comment]
hm yeah imo thats actually part of the game.. usually you never keep on jumping since thats pretty predictable.
So imo the only effect this would have is that begginners would jump all the time instead of their current behaviour running straight forward without any notice of anyone else. :rabbit:

**Comment by Croydon** [comment]
I agree with @a-teammate. Such a feature sounds misplaced.

**Comment by Croydon** [comment]
Since nobody else replied I guess I can say we rejected this suggestion (till somebody says something else..).
