### ISSUE TITLE
Don't try to load a missing model each frame

### ISSUE THREAD

**Issue by aschaeffer** [inexor-game/code#157]
Currently inexor tries to load a model if it isn't already loaded. But if the model isn't available on disk the next try will fail in every frame, which leads to performance issues.

* Add a flag in the model data structure for "loading failed"
* Don't load a missing texture another time, if the flag is set

**Comment by Croydon** [comment]
https://github.com/kripken/BananaBread/commit/59c9cda480ac04d22999eb97a013869203cb1893

**Comment by Fohlen** [comment]
Fixed with @60e561e

**Comment by Croydon** [comment]
You don't need to write the commit where it is done manually, if you have mentioned the issue in your commit message. GitHub is creating a reference for you :)

**Comment by Fohlen** [comment]
Good to know :+1:
