### ISSUE TITLE
Add contributing standards to code and data repository

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#161]
We should consider to add [contributing.md](https://github.com/necolas/issue-guidelines/blob/master/CONTRIBUTING.md) to the data and code repository.
This is a clean and usefull guideline for all further contributions and I personally think this could solve us a lot of issues which could have better been discussed in IRC (for example).

**Comment by aschaeffer** [comment]
Ok, but we already have a wiki entry:

https://github.com/inexor-game/code/wiki/How%20to%20contribute

The information about contributing should be in sync.

**Comment by Croydon** [comment]
Why is this closed? 
Afaik if there is a contributing.md file, people who creating a PR are getting displayed a link to it, so it would get much more attention. The contributing.md file shouldn't be a technical introduction how to contribute, but an explaination of our workflow and what we are requiring/accepting/denying.
