### ISSUE TITLE
Auto detection of data repositories

### ISSUE THREAD

**Issue by aschaeffer** [inexor-game/code#162]
Inexor supports multiple repositories (old term: "package folders"). Currently only the linux bash script has a detection mechanism for these repositories. We should make it cross platform by implementing in C++.

#### Auto Detection

1. Create an empty repositories/ folder in inexor-game/code if not already exists
2. On client startup, all folders below the repositories/ folder gets automatically detected
3. ~~Validation: These folders MUST contain a "config" and a "media" folder~~
4. The detected and validated folders are added as additional repository
5. Also add manually declared repository locations (command line option -k, also use validation)

#### Implementation

* Implementation in C++ instead of unix/windows shell scripts
* Ensure cross platform compatibility

#### Packaging

* During packaging, the core data repository (inexor-game/data) should be located at data/inexor-core or data/inexor-base

#### Future

* Provide a UI for management of data repositories
  * Enable, disable data repository
* Use a locally installed git (probably via Inexor's IPC interface) to add, remove and update remote git repositories

**Comment by Croydon** [comment]
Won't become the concept of different "repositories" obsolete when we add an ingame downloader?

**Comment by Croydon** [comment]
I'm closing this for now. Further major improvements are not really necessary and it's likely to become obsolete in the long run due to an ingame downloader and a new kind of content packages.
