### ISSUE TITLE
make newmap command work when being in (coop) editmode

### ISSUE THREAD

**Issue by obstriegel** [inexor-game/code#163]
Currently you can't start a new map when being in editmode.

20c2339dabd091d4694a96d047c2e9c7bd34f28f

Simply start a new map and try /newmap to reproduce.

**Comment by Croydon** [comment]
This isn't a bug. You need to toggle/enter the edit mode (not the coop game mode) if you want to start a new map and when you are already on a map. The behaviour didn't change in comparison to Sauerbraten.
