### ISSUE TITLE
Create an instructional beginner map with audio playbacks

### ISSUE THREAD

**Issue by aschaeffer** [inexor-game/code#165]
From @IAmNotHanni in #75:

> Maybe we could script a beginner map with audio playbacks. I am inspired by Portal in this aspect:
https://youtu.be/eFe3eKaKeF0?t=59s
> 
> This would be so awesome!

**Comment by Croydon** [comment]
In my opinion this issue is in the wrong repository. Technically it's already possible, so somebody needs just to build such a map and that belongs into inexor-game/data.
