### ISSUE TITLE
Refactor CMAKE platform detection

### ISSUE THREAD

**Issue by koraa** [inexor-game/code#169]
Cmake platform detection is pretty fucked right now;

The new, better one should replace the native cmake detection;
from now on we should use 3 stages:
1. ALWAYS detect host settings and store in HOST_\* variables
2. The platform file configures the target as specified on the command line, either by setting TARG_\* variables or for instance by setting the compiler or other stuff
3.  infer any TARG_\* variables that have not been set by the platform file; by default we are not cross compiling; in this case the TARG_\* variables are the same as the HOST_\* ones

Both host and target detection should be functions; so the build configuration or the platform files can decide at which point the detection should run.

Variables should at least indicate OS (-POSIX, -UNIX, -LINUX, -BSD, -DARWIN, -WINDOWS, -LINUX-UBUNTU, -LINUX-DEBIAN, -WINDOWS-XP, -WINDOWS-NT, ...), architecture (-i386, -i686, -x86_64, -x86, -32, -64) and compiler/linker types (-GCC, -GCC-REAL, -CLANG, -VS, -VS2013, -VS2015, ...)

**Comment by a-teammate** [comment]
I don't know why we should support any crossplatform-compilation by house at all. Especially at this stage.
I'd say its fine currently.

**Comment by Fohlen** [comment]
Closed by using conan.

**Comment by a-teammate** [comment]
Had nothing todo with conan, but I'd also say close this issue. Too much work, no gain.
