### ISSUE TITLE
Make the tests run with wine, on windows, and in the CI

### ISSUE THREAD

**Issue by koraa** [inexor-game/code#174]

**Comment by a-teammate** [comment]
done with 5df6f64db15087a1a597d772b414dbbb586beb1a

**Comment by koraa** [comment]
Did you test this?

**Comment by aschaeffer** [comment]
DONE: Tests are running on windows
DONE: Tests are running on CI
MISSING: Tests are running with wine

**Comment by a-teammate** [comment]
closed after long discussion since deprecated situation (we got a windows ci now) and we got #131 for the tests failing
