### ISSUE TITLE
Fix double input while running CEF

### ISSUE THREAD

**Issue by koraa** [inexor-game/code#177]
When running CEF, at least in wine, the normal console receives each character twice.
This is caused by SDL_ providing two SDL_TEXT events but not more than usual SDL_KEYUP/DOWN events.

Please check whether this problem also occurs on windows.

**Comment by aschaeffer** [comment]
Yes, it's complicated!

Short summary: we need to handle "SDL_TEXT" AND "SDL_KEYUP/SDL_KEYDOWN". Some characters are only available as SDL_TEXT event, others only as KEYUP or KEYDOWN and the rest spawns both events.

**Comment by koraa** [comment]
If I recall correctly, that was not quite the problem; The console input completely ignores SDL_KEYUP/DOWN and just uses SDL_TEXT; SDL_TEXT however occurred *twice* for each key press

**Comment by a-teammate** [comment]
maybe this helps: https://wiki.libsdl.org/MigrationGuide section **Input** ?

**Comment by Croydon** [comment]
Fixed *somewhen*, *somewhere*. *Somehow* related to #276.
