### ISSUE TITLE
Fix CEF crashing inexor on win/wine64

### ISSUE THREAD

**Issue by koraa** [inexor-game/code#178]
When CEF is started on wine/64 it crashes because of a SEGFAULT in libcef.dll. Investigate and fix.

Please verify whether this also occurs on windows.

**Comment by Croydon** [comment]
Are we talking about just starting inexor.exe? If yes, then I can't confirm that for Win7.

**Comment by Fohlen** [comment]
Can someone try to verify this error? Maybe it's caused by the same problem as in #226 and can therefore be closed?

**Comment by Croydon** [comment]
No answer from @koraa in _quite some time_.
Not reproducable at any time and we don't support Wine.
Bottom line: Was never a bug.
