### ISSUE TITLE
server needs SDL2 to build

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#194]
The server currently needs SDL2 to build ..
This should be fixed by -DSTANDALONE but somehow got lost with the introduction of cmake..

**Comment by koraa** [comment]
Moved here: https://github.com/inexor-game/code/issues/196

(this is not a bug)

**Comment by koraa** [comment]
@Fohlen You tried -DBUILD_CLIENT=false but it sill failed

**Comment by a-teammate** [comment]
the bug appears bc module_RPC would need to be built 2 times: one time for the server and one time for the client. (one with standalone and one without)
