### ISSUE TITLE
Re-introduce master into makefile

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#195]
Currently there is no make option to build a master-server..
We should think about integrating some sort of masterserver (see #20) or keeping the original master for the next few releases (until Alpha 0.3 or later) in regards to coming multiplayer in `Freeze`

**Comment by koraa** [comment]
Rejected. No more code-injecting cube script master.

Instead create a strong protocol in JS: https://github.com/inexor-game/code/issues/197

**Comment by aschaeffer** [comment]
Would it be possible to hardcode a server list until we have a replacement?

**Comment by koraa** [comment]
@aschaeffer Yes. If we really need a server list for I highly suggest we just create custom cubescript GUI for it.

**Comment by Fohlen** [comment]
Agree, we should close the issue in regard to #197
