### ISSUE TITLE
XMPP Integration (Masterserver, Chat, ...)

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#20]
As mentioned by @aschaeffer previously there should be made a strategic decision on further development of the masterserver. The following suggestions have been made so far:
- Replace the current implementation with a protocol ahead XMPP / Jabber
- Make a drop-in replacement using HTTP and JSON calls.

Probably we should open a voting here or in the wiki. Any comment's are highly appreciated!

**Comment by Fohlen** [comment]
I'd made a draft [on our pad](https://pad.inexor.org/p/Network_Draft) and would like to hear your opinions!

**Comment by a-teammate** [comment]
@Fohlen the draft pad does not work anymore! Could you reup it plz?

Moreover this issue is mostly outdated.

**Comment by Fohlen** [comment]
Closed in favor of the decentralized server list.
