### ISSUE TITLE
Use offical ENet repository as a submodule

### ISSUE THREAD

**Issue by Croydon** [inexor-game/code#202]
Since ENet is supporting itself CMake we shouldn't be in need of a fork of ENet anymore.
https://github.com/lsalzman/enet/commit/c8fa0aeea46d8ac00b2402f5ab7f09770837124a

We are using currently https://github.com/Theintercooler/enet

**Comment by aschaeffer** [comment]
:+1:

Agree, it shouldn't be much work anyways.

**Comment by aschaeffer** [comment]
reason for closing and "wontfix"?

**Comment by Croydon** [comment]
>(16:22:46) Fohlen: isn't that solved as well by relying to the enet library installed on the system (or a dll on windows) ?
(16:22:52) Fohlen: afaik
(16:29:17) a_teammate: true

**Comment by Croydon** [comment]
https://github.com/inexor-game/code/commit/1a79b552f2f17d190f3b205fd8b4dffe0b1788e5
