### ISSUE TITLE
CMake Configuration fails because of unset variable

### ISSUE THREAD

**Issue by Croydon** [inexor-game/code#203]
>CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PTHREADS_INCLUDE_DIRS
   used as include directory in directory C:/---/inexor-master/inexor/client
   used as include directory in directory C:/---/inexor/server

**Comment by koraa** [comment]
Try to set PTHREADS_INCLUDE_DIRS="" when starting CMake. If it still works, we can probably remove the var.

**Comment by Croydon** [comment]
When doing this I can generate the project but still can't compile with MinGW.

Error log:
>||=== Build: all in Inexor (compiler: GNU GCC Compiler) ===|
C:\---\inexor-master\inexor\libraries\googletest\include\gtest\internal\gtest-port.h||In constructor 'testing::internal::Mutex::Mutex()':|
C:\---\inexor-master\inexor\libraries\googletest\include\gtest\internal\gtest-port.h|1699|warning: 'testing::internal::Mutex::type_' will be initialized after [-Wreorder]|
C:\---\inexor-master\inexor\libraries\googletest\include\gtest\internal\gtest-port.h|1695|warning:   'unsigned int testing::internal::Mutex::owner_thread_id_' [-Wreorder]|
C:\---\inexor-master\inexor\libraries\googletest\src\gtest-port.cc|198|warning:   when initialized here [-Wreorder]|
C:\---\inexor-master\inexor\libraries\googletest\src\gtest-death-test.cc|123|warning: 'testing::internal::g_in_fast_death_test_child' defined but not used [-Wunused-variable]|
C:\---\inexor-master\inexor\net\MCHub.cpp|13|error: 'template<class Container> class inexor::net::MCHub' used without template parameters|
C:\---\inexor-master\inexor\net\MCHub.cpp||In function 'std::list<inexor::net::MessageConnect*>* inexor::net::connects()':|
C:\---\inexor-master\inexor\net\MCHub.cpp|14|error: 'cons' was not declared in this scope|
C:\---\inexor-master\inexor\net\MCHub.cpp|17|error: 'template<class Container> class inexor::net::MCHub' used without template parameters|
C:\---\inexor-master\inexor\net\MCHub.cpp||In function 'void inexor::net::Send(inexor::net::bytes&)':|
C:\---\inexor-master\inexor\net\MCHub.cpp|19|error: 'cons' was not declared in this scope|
C:\---\inexor-master\inexor\net\MCHub.cpp|24|error: invalid use of template-name 'inexor::net::MCHub' without an argument list|
C:\---\inexor-master\inexor\net\MCHub.cpp||In function 'std::list<inexor::net::MessageConnect*>* inexor::net::connects()':|
C:\---\inexor-master\inexor\net\MCHub.cpp|15|warning: control reaches end of non-void function [-Wreturn-type]|
inexor\net\CMakeFiles\module_net.dir\build.make|78|recipe for target 'inexor/net/CMakeFiles/module_net.dir/MCHub.cpp.obj' failed|
CMakeFiles\Makefile2|247|recipe for target 'inexor/net/CMakeFiles/module_net.dir/all' failed|
C:\---\inexor-master\build\Makefile|115|recipe for target 'all' failed|
||=== Build failed: 8 error(s), 5 warning(s) (0 minute(s), 28 second(s)) ===|

Complete build log:
>-------------- Build: all in Inexor (compiler: GNU GCC Compiler)---------------

Running command: C:/PROGRA~2/TDM-GC~1/bin/mingw32-make.exe -f "C:/Users/Michael/Desktop/inexor-master/build/Makefile"  VERBOSE=1 all
"C:\Program Files (x86)\CMake\bin\cmake.exe" -HC:\---\inexor-master -BC:\---\inexor-master\build --check-build-system CMakeFiles\Makefile.cmake 0
"C:\Program Files (x86)\CMake\bin\cmake.exe" -E cmake_progress_start C:\---\inexor-master\build\CMakeFiles C:\---\inexor-master\build\CMakeFiles\progress.marks
C:/PROGRA~2/TDM-GC~1/bin/mingw32-make.exe -f CMakeFiles\Makefile2 all
mingw32-make.exe[1]: Entering directory 'C:/Users/Michael/Desktop/inexor-master/build'
C:/PROGRA~2/TDM-GC~1/bin/mingw32-make.exe -f inexor\libraries\CMakeFiles\build_gtest.dir\build.make inexor/libraries/CMakeFiles/build_gtest.dir/depend
mingw32-make.exe[2]: Entering directory 'C:/Users/Michael/Desktop/inexor-master/build'
"C:\Program Files (x86)\CMake\bin\cmake.exe" -E cmake_depends "MinGW Makefiles" C:\---\inexor-master C:\---\inexor-master\inexor\libraries C:\---\inexor-master\build C:\---\inexor-master\build\inexor\libraries C:\---\inexor-master\build\inexor\libraries\CMakeFiles\build_gtest.dir\DependInfo.cmake --color=
mingw32-make.exe[2]: Leaving directory 'C:/Users/Michael/Desktop/inexor-master/build'
C:/PROGRA~2/TDM-GC~1/bin/mingw32-make.exe -f inexor\libraries\CMakeFiles\build_gtest.dir\build.make inexor/libraries/CMakeFiles/build_gtest.dir/build
mingw32-make.exe[2]: Entering directory 'C:/Users/Michael/Desktop/inexor-master/build'
mingw32-make.exe[2]: Nothing to be done for 'inexor/libraries/CMakeFiles/build_gtest.dir/build'.
mingw32-make.exe[2]: Leaving directory 'C:/Users/Michael/Desktop/inexor-master/build'
"C:\Program Files (x86)\CMake\bin\cmake.exe" -E cmake_progress_report C:\---\inexor-master\build\CMakeFiles  1 2 3 4 5 6 7
[  7%] 
Built target build_gtest
C:/PROGRA~2/TDM-GC~1/bin/mingw32-make.exe -f inexor\libraries\CMakeFiles\module_muparser.dir\build.make inexor/libraries/CMakeFiles/module_muparser.dir/depend
mingw32-make.exe[2]: Entering directory 'C:/Users/Michael/Desktop/inexor-master/build'
"C:\Program Files (x86)\CMake\bin\cmake.exe" -E cmake_depends "MinGW Makefiles" C:\---\inexor-master C:\---\inexor-master\inexor\libraries C:\---\inexor-master\build C:\---\inexor-master\build\inexor\libraries C:\---\inexor-master\build\inexor\libraries\CMakeFiles\module_muparser.dir\DependInfo.cmake --color=
mingw32-make.exe[2]: Leaving directory 'C:/Users/Michael/Desktop/inexor-master/build'
C:/PROGRA~2/TDM-GC~1/bin/mingw32-make.exe -f inexor\libraries\CMakeFiles\module_muparser.dir\build.make inexor/libraries/CMakeFiles/module_muparser.dir/build
mingw32-make.exe[2]: Entering directory 'C:/Users/Michael/Desktop/inexor-master/build'
mingw32-make.exe[2]: Nothing to be done for 'inexor/libraries/CMakeFiles/module_muparser.dir/build'.
mingw32-make.exe[2]: Leaving directory 'C:/Users/Michael/Desktop/inexor-master/build'
"C:\Program Files (x86)\CMake\bin\cmake.exe" -E cmake_progress_report C:\---\inexor-master\build\CMakeFiles  58 59 60 61 62 63 64
[ 14%] 
Built target module_muparser
C:/PROGRA~2/TDM-GC~1/bin/mingw32-make.exe -f inexor\util\CMakeFiles\module_util.dir\build.make inexor/util/CMakeFiles/module_util.dir/depend
mingw32-make.exe[2]: Entering directory 'C:/Users/Michael/Desktop/inexor-master/build'
"C:\Program Files (x86)\CMake\bin\cmake.exe" -E cmake_depends "MinGW Makefiles" C:\---\inexor-master C:\---\inexor-master\inexor\util C:\---\inexor-master\build C:\---\inexor-master\build\inexor\util C:\---\inexor-master\build\inexor\util\CMakeFiles\module_util.dir\DependInfo.cmake --color=
mingw32-make.exe[2]: Leaving directory 'C:/Users/Michael/Desktop/inexor-master/build'
C:/PROGRA~2/TDM-GC~1/bin/mingw32-make.exe -f inexor\util\CMakeFiles\module_util.dir\build.make inexor/util/CMakeFiles/module_util.dir/build
mingw32-make.exe[2]: Entering directory 'C:/Users/Michael/Desktop/inexor-master/build'
mingw32-make.exe[2]: Nothing to be done for 'inexor/util/CMakeFiles/module_util.dir/build'.
mingw32-make.exe[2]: Leaving directory 'C:/Users/Michael/Desktop/inexor-master/build'
"C:\Program Files (x86)\CMake\bin\cmake.exe" -E cmake_progress_report C:\---\inexor-master\build\CMakeFiles  83
[ 15%] 
Built target module_util
C:/PROGRA~2/TDM-GC~1/bin/mingw32-make.exe -f inexor\net\CMakeFiles\module_net.dir\build.make inexor/net/CMakeFiles/module_net.dir/depend
mingw32-make.exe[2]: Entering directory 'C:/Users/Michael/Desktop/inexor-master/build'
"C:\Program Files (x86)\CMake\bin\cmake.exe" -E cmake_depends "MinGW Makefiles" C:\---\inexor-master C:\---\inexor-master\inexor\net C:\---\inexor-master\build C:\---\inexor-master\build\inexor\net C:\---\inexor-master\build\inexor\net\CMakeFiles\module_net.dir\DependInfo.cmake --color=
mingw32-make.exe[2]: Leaving directory 'C:/Users/Michael/Desktop/inexor-master/build'
C:/PROGRA~2/TDM-GC~1/bin/mingw32-make.exe -f inexor\net\CMakeFiles\module_net.dir\build.make inexor/net/CMakeFiles/module_net.dir/build
mingw32-make.exe[2]: Entering directory 'C:/Users/Michael/Desktop/inexor-master/build'
"C:\Program Files (x86)\CMake\bin\cmake.exe" -E cmake_progress_report C:\---\inexor-master\build\CMakeFiles 66
[ 16%] 
Building CXX object inexor/net/CMakeFiles/module_net.dir/MCHub.cpp.obj
cd /d C:\---\inexor-master\build\inexor\net && C:\PROGRA~2\TDM-GC~1\bin\G__~1.EXE   -DASIO_STANDALONE -DNOMINMAX -DWIN32 -DWIN64 -DWINDOWS -D_FILE_OFFSET_BITS=64 -D_WIN32 -D_WIN32_WINNT=0x0501 -D_WINDOWS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -fomit-frame-pointer -fno-strict-aliasing -fsigned-char -pipe -Wall -Wno-switch -Wno-deprecated-declarations  -fdiagnostics-show-option  -m64 -march=x86-64 -fno-threadsafe-statics -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0  -O0 -g -D_DEBUG  @CMakeFiles/module_net.dir/includes_CXX.rsp   -o CMakeFiles\module_net.dir\MCHub.cpp.obj -c C:\---\inexor-master\inexor\net\MCHub.cpp
C:\---\inexor-master\inexor\net\MCHub.cpp:13:26: error: 'template<class Container> class inexor::net::MCHub' used without template parameters
   list<MessageConnect*>* MCHub::connects() {
                          ^
C:\---\inexor-master\inexor\net\MCHub.cpp: In function 'std::list<inexor::net::MessageConnect*>* inexor::net::connects()':
C:\---\inexor-master\inexor\net\MCHub.cpp:14:12: error: 'cons' was not declared in this scope
     return cons;
            ^
C:\---\inexor-master\inexor\net\MCHub.cpp: At global scope:
C:\---\inexor-master\inexor\net\MCHub.cpp:17:8: error: 'template<class Container> class inexor::net::MCHub' used without template parameters
   void MCHub::Send(bytes &dat) {
        ^
C:\---\inexor-master\inexor\net\MCHub.cpp: In function 'void inexor::net::Send(inexor::net::bytes&)':
C:\---\inexor-master\inexor\net\MCHub.cpp:19:16: error: 'cons' was not declared in this scope
     for (itr = cons->begin(); itr != cons->end(); itr++)
                ^
C:\---\inexor-master\inexor\net\MCHub.cpp: At global scope:
C:\---\inexor-master\inexor\net\MCHub.cpp:24:3: error: invalid use of template-name 'inexor::net::MCHub' without an argument list
   MCHub::bytes_on_channel MCHub::ReceiveChannel() {
   ^
C:\---\inexor-master\inexor\net\MCHub.cpp: In function 'std::list<inexor::net::MessageConnect*>* inexor::net::connects()':
C:\---\inexor-master\inexor\net\MCHub.cpp:15:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
mingw32-make.exe[2]: *** [inexor/net/CMakeFiles/module_net.dir/MCHub.cpp.obj] Error 1
mingw32-make.exe[1]: *** [inexor/net/CMakeFiles/module_net.dir/all] Error 2
mingw32-make.exe: *** [all] Error 2
inexor\net\CMakeFiles\module_net.dir\build.make:78: recipe for target 'inexor/net/CMakeFiles/module_net.dir/MCHub.cpp.obj' failed
mingw32-make.exe[2]: Leaving directory 'C:/Users/Michael/Desktop/inexor-master/build'
CMakeFiles\Makefile2:247: recipe for target 'inexor/net/CMakeFiles/module_net.dir/all' failed
mingw32-make.exe[1]: Leaving directory 'C:/Users/Michael/Desktop/inexor-master/build'
C:/Users/Michael/Desktop/inexor-master/build/Makefile:115: recipe for target 'all' failed
Process terminated with status 2 (0 minute(s), 1 second(s))
8 error(s), 1 warning(s) (0 minute(s), 1 second(s))

**Comment by koraa** [comment]
Which branch are you compiling on? Which GCC version are you using? Which mingw version?

**Comment by Croydon** [comment]
It's the master branch ofc.
The above stuff did happened with GCC 4.9.2.

In the meantime I updated to MinGW-W64-builds-4.2.0 with GCC 5.1.0 
I have set PTHREADS_INCLUDE_DIRS="" and get this on the first run:

>Looking for include file pthread.h
Looking for include file pthread.h - found
Looking for pthread_create
Looking for pthread_create - not found
Check if compiler accepts -pthread
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   THREADS_PTHREAD_ARG (advanced)
For details see C:/Users/Michael/Desktop/inexor-clean/build/TryRunResults.cmake
Check if compiler accepts -pthread - no
Found Threads: TRUE  
DETECTING 1 :  : 1
threadapi=pthreads
THREADAPI : pthreads : 1 :  :  : 

Complete CMake logs here: https://gist.github.com/Croydon/4b48dfb568c9aba5239b

However, if I just rerun the configuration without changing anything, no errors come up, I can generate the CodeBlocks project, compile it and start Inexor. But always just on the second configuration run and with PTHREADS_INCLUDE_DIRS="".

**Comment by Croydon** [comment]
Fixed as of https://github.com/inexor-game/code/commit/f8327a3fc67a333abe4008a970c515964db5fd4d
