### ISSUE TITLE
Problems with naming

### ISSUE THREAD

**Issue by IAmNotHanni** [inexor-game/code#206]
We must be careful when using drug names for our releases.
Ritalin is actually a trademark of the swiss pharmaceutical company Novartis!

https://en.wikipedia.org/wiki/Methylphenidate
https://en.wikipedia.org/wiki/Novartis

We will never have problems if we use international IUPAC names for chemical compounds, but they are in most cases complicated and very long.

**Comment by aschaeffer** [comment]
Ok :-) Thanks for the ~~fish~~ hint. But... what do you expect we should do now?

**Comment by Croydon** [comment]
I guess we have to be more careful in the future. However, in less than a month we already have a new release and so a new name. Also as a non-commerical game we are not even close to the commerical pharmaceutical industry. Nobody will confuse the one thing with the other, so we should be fine.

**Comment by Fohlen** [comment]
We can use "street-names" like eg:
speed / pep instead of alpha‑methylphenethylamine,
dope instead of Tetrahydrocannabinol ..
and so on ;)

**Comment by Boom-Rang** [comment]
That's what I was suggesting in IRC, you could say Molly/Mandy instead of N-methylpropan-2-amine (MDMA)
