### ISSUE TITLE
CMake Support for Eclipse CDT4

### ISSUE THREAD

**Issue by aschaeffer** [inexor-game/code#207]
When initializing the build directory...

    mkdir build
    cd build
    cmake -G"Eclipse CDT4 - Unix Makefiles" ..

... I get the following warning:

    CMake Warning in CMakeLists.txt:
      The build directory is a subdirectory of the source directory.
    
      This is not supported well by Eclipse.  It is strongly recommended to use a
      build directory which is a sibling of the source directory.

**Comment by koraa** [comment]
This warning pretty clearly states what you need to do?

```
$ mkdir ../inexor-build
$ cd ../inexor-build
$ cmake ../inexor
```

**Comment by aschaeffer** [comment]
Ok, thanks.

We should document this anyway:
https://github.com/inexor-game/code/wiki/Build#linux
