### ISSUE TITLE
Provide linux release(s)

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#208]
We could overcome future build problems with static linux binaries by providing custom distribution builds
This could be easily done by:
* Setting up Jenkins
* Using the [Debian Package Builder](https://wiki.jenkins-ci.org/display/JENKINS/Debian+Package+Builder+Plugin)
* Provide a custom PPA on Debian Testing, Launchpad (...)
* Additonally we can maintain our own stable enet PPA (cloned from Git)
* Might need some custom buildscripts for Cent and Arch

**Comment by aschaeffer** [comment]
A PPA would be nice!

We have a issue for jenkins already: #23

Jenkins & RPM: http://www.itforeveryone.co.uk/rpm-build-hudson-jenkins.html
Jenkins & CMake: https://wiki.jenkins-ci.org/display/JENKINS/cmakebuilder+Plugin

**Comment by Fohlen** [comment]
There is also a possibility to do this using travis-ci, although it's not that easy..

**Comment by Croydon** [comment]
Please provide always a quick ref to the other issue if it's a duplicated. What is the other issue?

**Comment by Fohlen** [comment]
Jenkins. And that' specifically what we need..

**Comment by Croydon** [comment]
Yeah, but there is a difference between setting up Jenkins (#23) and making Linux binaries portable, so that we can actually provide them?

**Comment by Fohlen** [comment]
We're building per-distribution package for the major distributions (Ubuntu, Cent, Fedora, Arch)
