### ISSUE TITLE
Work around libudev naming issues

### ISSUE THREAD

**Issue by koraa** [inexor-game/code#209]
We ran into this  problem: http://magpcss.org/ceforum/viewtopic.php?f=6

Our libcef.so is built with libudev.so.0. However, libudev was renamed to libudev.so.1 on some systems.

Work around this by explicitly linking against libudev:
* Write a libudev_config in the libraries CMake file
* This just searches for libudev `find_libs(UDEV_LIBS udev)` and links against them
* Call libudev_config from the cef_config for the passed target and for the ui_module, so we get rid of the linker error

It might still show an error that libudev.so.0 was not found; if so, find out why.

**Comment by koraa** [comment]
@Fohlen Another question: Did that occur during compilation or at runtime?

**Comment by Fohlen** [comment]
Am 24.08.2015 um 13:15 schrieb Karolin Varner:
>
> @Fohlen <https://github.com/Fohlen> Another question: Did that occur
> during compilation or at runtime?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inexor-game/code/issues/209#issuecomment-134156162>.
>
During compilation

**Comment by koraa** [comment]
ok. good.

**Comment by Boom-Rang** [comment]
Not a real long term solution but this worked for me:
```bash
sudo ln -sf /lib/$(arch)-linux-gnu/libudev.so.1 /lib/$(arch)-linux-gnu/libudev.so.0
```
Installing the actual package (for ubuntu http://packages.ubuntu.com/precise/libudev0) with:
```bash
dpkg -i libudev0_175-0ubuntu9_*.deb
```
is probably a cleaner option

**Comment by Fohlen** [comment]
I can confirm this workaround.
The best solution would be writting a config in CMake for libudev and libcef

**Comment by Fohlen** [comment]
#215
