### ISSUE TITLE
Aquarust Release binary fails on Windows 8 and higher

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#213]
I've been reported (multiple times) that Aquarust fails to start with the following message on Windows 8 and higher

```
 [10:02] Harsh: libgcc_s_seh-1.dll is missing from your computer 
 [10:02] Harsh: libstdc++-6.dll is missing from your computer
```
Can anyone, maybe @Croydon confirm this bug? How do we get rid of it?

**Comment by M0UL** [comment]
i am have the same problem on windows 10.
i am geting these errors: http://imgur.com/XxolF1r
the game doesnt even start, i am not even geting a log file

**Comment by Croydon** [comment]
Does somebody else has a Windows 7 setup so that we can confirm that it is a Win8+ only bug?

**Comment by a-teammate** [comment]
this issue appears bc you compile with mingw and do not link statically (or deploy your shared standard lib, which is probably not the best idea i guess).
use vs studio builds and everything is fine (in release mode only)

**Comment by a-teammate** [comment]
updated the bins
