### ISSUE TITLE
Undo bug

### ISSUE THREAD

**Issue by SF-Fatality** [inexor-game/code#216]
Not sure if it is just my client, but when in coop mode, if I try to use /undo by pressing Z, the game crashes.

**Comment by Croydon** [comment]
Can't reproduce. @SF-Fatality Please try it again with a newer version.

Anybody else who can reproduce this?

**Comment by Fohlen** [comment]
Fixed somewhen and somewhere. This does work on Windows and Linux (latest branches). I just tested it with @basile-henry

**Comment by SF-Fatality** [comment]
Seems fixed to me :)
