### ISSUE TITLE
/replace bug

### ISSUE THREAD

**Issue by SF-Fatality** [inexor-game/code#217]
When I use the command "/replace" after making a texture change, the game crashes.

**Comment by Fohlen** [comment]
Fixed somewhen and somewhere. This does work on Windows and Linux (latest branches). I just tested it with @basile-henry

**Comment by Croydon** [comment]
@SF-Fatality Please provide still feedback at some point if it is fixed for you as well. Thanks.

**Comment by SF-Fatality** [comment]
Seems fixed to me :)
