### ISSUE TITLE
start node.js automatically within inexor

### ISSUE THREAD

**Issue by a-teammate** [inexor-game/code#218]
People do not want to start 2 batches and since that will be the first issue people will have in mind thinking of "node.js outside not inside inexor" it will be best for the acceptance of this technology to resolve that pretty soon (since we need to do that anyway, but the earlier the better imo, since more people will feel attracted towards working with it the easier it gets)

**Comment by Fohlen** [comment]
Furthermore we should inbuilt RPC into the server as it's currently not added..
