### ISSUE TITLE
Fixing CMake for hanni/3DVisualScripting branch

### ISSUE THREAD

**Issue by IAmNotHanni** [inexor-game/code#221]
I've had trouble for one month with CMake now.
I have now idea how it works or whats wrong, but atm it just can't find SDL(2).

The error's source must be cube.h somehow.
I need your help.

**Comment by IAmNotHanni** [comment]
"SDL.h" not found also occurs in other modules such as module_ui

**Comment by Croydon** [comment]
@IAmNotHanni Works fine for me. Is this still an issue?
