### ISSUE TITLE
getmap is trying to load nonexistence local map 

### ISSUE THREAD

**Issue by SetZero** [inexor-game/code#222]
If you try to load a sent map on a server which has already set the name of the map it will try to load the local version of this map insted of the server version (even if the map name is getmap_xyz). 

A temporary workaround for this bug is sending  the map, starting a new map and then getting the map. This has to be done everytime someone new joins the game as he doesn't have the local version of this map and the mapname will be set to getmap_xyz after sentmap.
This most likely works because after starting a new map the name of the map is not set and so it won't look for a nonexistence local version of this map, but instead it will ask the server for the newest version. (At least that's my guess)

**Comment by IAmNotHanni** [comment]
Confirmed.
Thanks for your support!

**Comment by Croydon** [comment]
@SetZero Should be fixed now. Happy editing, if you run into further problems let us know please :)
