### ISSUE TITLE
Porting Inexor to Andoid?

### ISSUE THREAD

**Issue by IAmNotHanni** [inexor-game/code#224]
One of my friends asked me if we could port Inexor to Android (because he has a NVIDIA Shield).
I think we have a pretty good code base for that, but superTux said Android has a simplified OpenGL support.

What do you say?

**Comment by Fohlen** [comment]
In my humble opinion we should NOT focus on this. It's moreover important to get our game running in the get-go on Windows, Linux and OSX now..

**Comment by Croydon** [comment]
I agree with Fohlen. This could be a thing for later.

**Comment by a-teammate** [comment]
agree with that. and imo no, thats not a thing for later..
