### ISSUE TITLE
Inexor not running on Arch because of protobuf

### ISSUE THREAD

**Issue by movabo** [inexor-game/code#225]
When trying to run inexor from the nightly-site i get the error:

```
CALLING: ./bin/linux/x86_64/inexor
./bin/linux/x86_64/inexor: error while loading shared libraries: libprotobuf.so.8: cannot open shared object file: No such file or directory
```

I installed the 
Protobuf-Lib from the AUR: https://www.archlinux.org/packages/extra/x86_64/protobuf/
But as you can see at the [files list](https://www.archlinux.org/packages/extra/x86_64/protobuf/files/) it does not include a libprotobuf.so.8, only the newer 9 version.

I also tried symlinking libprotobuf.so.9 to libprotobuf.so.8 (hoping it was backwards-compatible or so ;-) ) but - as expected - it was not. Error message: 
```
CALLING: ./bin/linux/x86_64/inexor
./bin/linux/x86_64/inexor: symbol lookup error: ./bin/linux/x86_64/inexor: undefined symbol: _ZN6google8protobuf8internal12kEmptyStringE
```

I'm running
```
$ uname -a
Linux <hostname> 4.1.6-1-ARCH #1 SMP PREEMPT Mon Aug 17 08:52:28 CEST 2015 x86_64 GNU/Linux
```
using
```
$ pacman -Q | grep protobuf
protobuf 2.6.1-1
```

**Comment by koraa** [comment]
That's quite possible. Please recompile with the libprotobuf.so provided on your system.

This is definitely a problem in the build system, which should be fixed by compiling our binaries with static libprotobuf.

Thanks for reporting.

**Comment by koraa** [comment]
btw, I can totally confirm this since I am on arch

**Comment by PowerKiller** [comment]
[pk@tuxybuxy tool]$ pacman -Q | grep protobuf
protobuf 2.6.1-1
protobuf-c 1.1.1-1

I compiled it with my protobuf and it worked... BTW, the repo you used for protobuf is NOT AUR

**Comment by Fohlen** [comment]
@PowerKiller thank you for the input. The shared libraries used referring to google/protobuf

**Comment by PowerKiller** [comment]
ah
