### ISSUE TITLE
Re-opening 3DVisualScripting

### ISSUE THREAD

**Issue by IAmNotHanni** [inexor-game/code#230]
master is far ahead of me and I can't fix flowgraph's, geom's or bezier's dependencies.
So here is my plan: Im going to delete the 3DVisualScripting branch but keep my work locally.
I am going to re-open the branch and import my work in my Visual Studio project file.
Im going to work locally and I will commit everything.
Once my work is more or less done I will push and those who have experience should write that CMake stuff.

**Comment by Croydon** [comment]
I guess you could have write this just in #221. Why an extra issue?
