### ISSUE TITLE
Merge.

### ISSUE THREAD

**Issue by PowerKiller** [inexor-game/code#234]
GitHub doesn't allow merging repos which aren't forks.. But couldn't fork as I couldn't have 2 forks.
Please run merge https://github.com/PowerKiller/inexor-code2 and this repo.

**Comment by koraa** [comment]
I am not sure where you're getting at. I suggest you create a branch in your first clone so you can avoid using two repos.

**Comment by PowerKiller** [comment]
hm, 'k, I thought making two repos would be cleaner.
