### ISSUE TITLE
CEF is not displaying anything

### ISSUE THREAD

**Issue by Croydon** [inexor-game/code#237]
Research + fix. Currently it doesn't seem to work for everyone.

If you want to try it do this:
1) Start node.js (with inexor_node_unix or inexor_node_windows.bat)
2) Start Inexor
3) Type in the console: /subsystem_start cef

If somebody get something displayed let us know please.

CEF log on Windows: https://gist.github.com/Croydon/26956a04359aeece6c24

**Comment by Fohlen** [comment]
Works for me
![4b2umyr](https://cloud.githubusercontent.com/assets/3730888/11163374/06b6741c-8acd-11e5-817f-4f5c5e11ff2f.png)

**Comment by aschaeffer** [comment]
This is fixed in karo+fohlen+hanack/fix_cef
