### ISSUE TITLE
Ambiant occlusion and invisible skytexture

### ISSUE THREAD

**Issue by basile-henry** [inexor-game/code#239]
I think ambiant occlusion shouldn't be taking into account invisible textures.
[Here](http://imgur.com/a/jNJfe)'s the effect on a common technique used by mappers to make ladders.

**Comment by chasester** [comment]
use an aphed material over the sky texture to remove any unwanted lighting effects. This should be kept this way to allow people to make invisible walls that only cast shadows. You see this trick used on almost every map that uses sky texture as an invisible no-render preset.

chasester

**Comment by basile-henry** [comment]
@chasester Thanks for your reply. Alpha material did the trick! :+1: I wasn't aware that this was common practice. I also didn't think this would solve the AO problem since it's not really calculated like a shadow.
