### ISSUE TITLE
The shell script doesn't work properly on archlinux

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#245]
As reported by @DjangoAsyl the libudev fix within `inexor_unix` will not work on any distribution except Debian/Ubuntu since the library is explicitly linked against `lib/arch/` but this does differ on various  distributions. On Arch the path is accordingly `/usr/lib`
We should find a way to resolve this issue once and for all by upgrading to a newer CEF version which compiles against a more recent ABI of libudev.

**Comment by Croydon** [comment]
Update CEF to a more recent version #271

**Comment by Croydon** [comment]
Can be closed?

**Comment by Fohlen** [comment]
Afaik can be closed. Work's properly for me using master branch.
