### ISSUE TITLE
reorder repository structure

### ISSUE THREAD

**Issue by a-teammate** [inexor-game/code#247]
We should update our structure of our files:

* move `platform` and `libraries` outside of the `inexor`-source folder
  * ( just move them one step up)
* move the `config` folder from data to `code` since theyre actually source files
  * then we can create a true structure inside Inexor/data with different media folders ('core', 'additional', 'playground' ) in there. related to #162

**Comment by koraa** [comment]
which config folder? There is no config folder in my repo.

**Comment by Croydon** [comment]
-> https://github.com/inexor-game/code/issues/162#issuecomment-160668182
+
the new UI is located in the code repo anyway, while the old Cubescript files will getting deleted at some point. Is it really necessary to move them now?

**Comment by DarkDeepBlue** [comment]
@koraa: The config folder was in the data repository before commit inexor-data@557ba8d.

**Comment by Croydon** [comment]
Done!
