### ISSUE TITLE
Potential bug in Sauerbraten / Inexor

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#251]
alebrije reported a potential bug that's present in Inexor/sauerbraten, which we've heard about before.
See this thread for further information -> http://sauerworld.org/forum/index.php?topic=374.msg2088#msg2088

It is reported that some maps, when you let bots walk for certain time, it will lead towards a crash.
Can anyone reproduce this error? Maybe @basile-henry who has expierenced this bug earlier.
How can we investigate this error? Any idea what potentially could cause that?

**Comment by basile-henry** [comment]
I just tested it again on the latest master and it seems fine. It's not easy to test since it's a bit random where the bots decide to go. The problem we used to have had to do with waypoints, if I recall correctly it was fixed in this commit: a32ccaf578839

**Comment by chasester** [comment]
This error is basid on some values set in the external libraries in sauer, and only occurs in debug mode. It happens mostly in ctf mode, and has something to do with array looping. In release mode this never happens. (I found this bug when building for sauerx).

**Comment by petrpisaratlascz** [comment]
I also experience this bug in Sauerbraten recently. It crashes in CHECKCLOSEST() macro, src/fpsgame/waypoint.cpp file, when accessing waypoints vector member on ridiculously large index. Glimpse on latest Sauerbraten's sources indicates the macro was corrected to check the index against the vector length first by commit r5006 (waypoint cache fixes).

**Comment by petrpisaratlascz** [comment]
And it fixes the crash for me.

**Comment by a-teammate** [comment]
a very nice, so we can close this
thank you all.

closed with 197920aa2dbd5da3a16e32bd7c86b8cab866bc76

**Comment by Croydon** [comment]
Afaik @basile-henry has experienced this bug long after the first alpha or 197920a. So at least in his case the bug was caused and/or fixed by something else.
