### ISSUE TITLE
Offer some delivery site similliar to cefbuilds.com

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#258]
_From @Fohlen on October 9, 2015 17:14_

What about using some frontend page to offer nightly builds? The plain FTP folder looks a little scary for everybody outside the project though..
cefbuilds.com is a great example imho..

_Copied from original issue: inexor-game/services#11_

**Comment by Fohlen** [comment]
_From @Croydon on October 9, 2015 17:46_

If you know how to do something like that with the Adrive APIs then just go for it :+1:

**Comment by Croydon** [comment]
Closed in favor of #269.
