### ISSUE TITLE
Propose an API for proccessing masterserver-requests

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#259]
_From @Fohlen on December 5, 2015 20:24_

We should yet plan about an API that can handle RESTfull requests as a masterserver.
As soon as CEF and NodeTree become available, we will be able to use those components to obtain a masterserver via a HTTP-crafted API (e.g delivering `.json` files which can be easily redistributed).
F3 provides object-mapping, so is very much likely to do the job. Furthermore it also brings support for DNSBL, which should protect us from spamming, a lot.
An example flow is given below

```
server -> registers at inexor.org
inexor.org -> sends the current-state masterlist as a .json file
----
client -> pings inexor.org
inexor.org -> sends the current masterlist as a .json file
----
client -> pings inexor.org OR any known server for a master.json
master or server -> sends a mirrored version master.json
----
server -> syncs master.json with inexor.org (using a checksum)
----
inexor.org may additionally add servers that have not registered themselves in the network. This is the case if inexor.org has been offline for a longer period, and a server therefore couldn't register himself. Anyhow server can ping other nodes in the network, and keep master.json self-repairing until inexor.org spins up again
```

This approach brings us a few advantages
- we do establish a network system with a redistributable masterlist, self-repairing
- we can protect ourselves from spam abuses using DNSBL and custom blacklists
- if necessary, we can outsource the masterlist to a CDN, since we're dealing with HTTP here

and a sole disadvantage that we probably need to talk about
- inexor.org serves as the initial _"entry-point"_, which partly brings back a centralized system

_Copied from original issue: inexor-game/website#32_

**Comment by aschaeffer** [comment]
Using the inexor,tree and the tree REST API the server list synchronization can easily be done.

See: https://pad.inexor.org/p/uibasics

**Comment by aschaeffer** [comment]
https://github.com/inexor-game/code/wiki/Decentralized-server-list

**Comment by Fohlen** [comment]
This will in future be handled via [self-regulating distributed networks](https://github.com/inexor-game/code/wiki/Self-regulating-distributed-network)
