### ISSUE TITLE
Add a unit-testing pattern

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#261]
_From @Fohlen on December 5, 2015 20:11_

We should agree on a pattern for unit-testing our controllers separately.
This could be done by implementing a base class containing a `::afterRoute()` method which is called within our controllers. The specific `afterRoute` method could be feeded with prepared results (in a `.json` file) and compare the actual output with the examples. Using such a design pattern would allow us to test and evaluate every controller separately from the MVC pattern, which comes handy for any future bugs.

_Copied from original issue: inexor-game/website#31_

**Comment by Croydon** [comment]
Please don't close issues without explanation.

**Comment by Fohlen** [comment]
https://vuejs.org/v2/guide/unit-testing.html is the pattern when using `Vue.js`
