### ISSUE TITLE
Use submenus to extend features

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#265]
_From @Fohlen on November 30, 2015 14:29_

What do you think of using submenu's to point out specific features within our navigation.
Might look like

Home
Blog
   -Community
   -Archive
Download
   -Release
   -Nightly

_Copied from original issue: inexor-game/website#28_

**Comment by Croydon** [comment]
Please don't close issues without explanation.

**Comment by Fohlen** [comment]
This is part of bootstrap 4 and needs no more implementation on our side.
