### ISSUE TITLE
Add a login-system

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#266]
_From @Fohlen on November 30, 2015 14:27_

Add a login bar into our menu (it should contain a gravatar-driven profile picture).
Login should be based on OpenID (OAuth-driven), which is supported by F3.

Members from Github with a specific OAuth ID (we can add a team.json adjustment) should be able to create a markdown patch with a WYSIWYG editor from the website.
This would come handy for many members to productively contribute to the blog.

In further development I'd like to use this technique to offer access via server-side OAuth, which would give us possibilities to create a statistical tracker (and whatsoever we like).

_Copied from original issue: inexor-game/website#27_

**Comment by Fohlen** [comment]
This should not be necessary on the main site.
Logins are handled by:

- Git and GitHub in terms of the content
- Disqus in terms of comments
- OAuth for repositories, competitive (however, this is not part of the main site)

**Comment by Croydon** [comment]
At least not necessary for now. I guess that will change in the future.
