### ISSUE TITLE
Add a commenting system

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#267]
_From @Fohlen on November 30, 2015 14:21_

Add a commenting system using either
- F3's built-in database, called _JIG_
- A redis adapter, since we use redis-db

Furthermore this system should allow trace- and pingbacks for improved blogging experience.
The RSS feed should be extended for comments as well (TODO)

_Copied from original issue: inexor-game/website#26_

**Comment by MartinMuzatko** [comment]
Muut.com?
Disqus.com?

**Comment by Fohlen** [comment]
https://disqus.com/ currently seems the de-facto standard if we don't want to host things ourselves. Therefore I'm giving that a try.

**Comment by Fohlen** [comment]
Disqus has been chosen with a `switch` button that is disabled by default in order to protect user privacy. Since Disqus offers extensive API's and ways to export posts, it is an alright choice before we plan to do something ourselves.
