### ISSUE TITLE
Create an own inclusion standard

### ISSUE THREAD

**Issue by Croydon** [inexor-game/code#270]
Created original by @Croydon
>Explain in a wiki page what standards content (maps, sounds, skyboxes..) have to accomplish to get offical content (besides the license policy of course). For a reference: http://quadropolis.us/node/3186
Pad: https://pad.inexor.org/p/Inexor_Inclusion_Standard

Written original by @SF-Fatality:
>I came up with some standards for maps. These are what I believe are important for included maps. Let me know what you think!
Inclusion Standards for SauerFork (Maps)
The following are basic guidelines to follow if you want a map included in the release of SauerFork. Please refer to eihrul's inclusion standards for Sauerbraten for a better understanding of what is expected.
1. Most important, the map should be built correctly. This includes using large grid sizes as often as possible and building to the grid. Building a map the right way can not only reduce the file size and load time, but most importantly will prevent unnecessary amounts of lag while playing your map. To see how to properly build a map, check out this video on map optimization. [Link to be added]
2. Stick to the game mode you want the map to be for. For example: a crazy maze-like layout might be nice for capture, but horrible for CTF; skip the flags if your map is for anything but CTF. Insta maps are best when pretty open and not too much clutter, FFA maps are usually a bit more complex. Keep in mind that no one wants to get lost while trying to play your map. It should be enjoyable 100 percent, so avoid things like dead ends if they don't fit the game mode, confusing hallways, anything that is a distraction from the fun of the game. If you are going to make a super complex layout, make sure it flows nicely, and have some landmarks to make the layout easier to remember after only a few times playing it. Maps where every wall and room look exactly the same are not only boring but also hard to stay oriented in. Keep the navigating of your map as simple as possible.
3. Create waypoints and drop well placed puck-ups. Placing ammo pickups, armor, and health is an art form in itself. Really pay attention to where you place them and how they could affect the gameplay. Even if your map will never be played with bots, or on a mode that uses items, it is good to have them on the occasion that they are.
4. Use appropriate lighting. We've all seen maps which are so dark you can barely see the walls and details, and maps which are so bright you can't even see your own cross hair. Remember that the main goal of a playable map is to appeal to your audience in every way possible. Players expect nothing short of the best experience while playing a map, after all that's what gaming is all about. Even one small distraction like improper lighting can deem your map completely unplayable. Even if your map has an great layout.
5. Avoid spamming particles, textures, and map models. Particles are a nice touch to some maps, but they can also be very distracting and lazy when spammed too much. They also have a tendency to cause FPS drops on lower end systems. Not to mention it looks pretty nooby when the focus of your map is the amount of particle spam. To go along with that, unless your map includes buildings made of bricks, spamming the same texture everywhere in your map also can be pretty bad. When every wall looks the same, it can be very confusing for a player trying to learn your map. Map models should also be used sparingly, and should not be the thing that makes your map. If it looks awesome until you do a /mapmodelreset, try cutting down on the map models. They are also not affected by /texreduce, so they will stand way out to someone who plays with reduced textures.
6. Focus on uniqueness. No one wants to play the same theme over and over with slightly different layouts. Try to come up with an awesome idea or theme before you even start your map, something that hasn't been done before. Anything is possible, and you don't need to follow the template of maps before you, just make anything that comes to mind and the gameplay and layout will come naturally. You will be surprised with the possibilities creating completely original content allows. 
7. Put in the work and time. Remember that a good map is a piece of art, so spend some time on it! Do your homework and take a look at your map from an outsider's view point. Is it really a good map? Take pride in your work and consider every one a masterpiece. Even when you think you are finally done, let it sit for a while after you think you've finished, and you might be surprised when you come back to it and notice things you missed the first time through. 
Good luck and have fun creating maps!
EDIT: Here is the "to be added" video: https://www.youtube.com/watch?v=clWyKy5eRnQ&feature=youtu.be

Original written by @killme:
> :+1:

Original written by @Croydon:
>Very nice work so far! I have set up a pad so it's easier to work together on it. 
https://piratenpad.de/p/SauerbratenForkInclusionStandard
Im not sure if the browser language gets detected automatically, if not you can choose your language by clicking on the wheel icon. 

Original written by @aschaeffer:
>:+1:
* Textures should be of high quality (min 1024px), downscaling is always possible
* Textures should always contain mipmaps (see http://en.wikipedia.org/wiki/Mipmap)
* Textures should contain a heightmaps
* Textures should be reusable on different maps
* Models should be optimized for few polygons for performance reasons

Original written by @koraa:
>We might consider providing a system to maintain multiple versions of a model with different quality.

Original written by @aschaeffer:
>:+1:
We discussed the same topic for textures yesterday:
* user can set the texture quality in the settings
* the texture downloading mechanism only fetches the textures in the required quality (-> so we can save a lot of bandwidth)

Original written by @Croydon:
>Updated pad to https://pad.inexor.org/p/Inexor_Inclusion_Standard

Original written by @a-teammate:
>Actually we do not need the point
* ~~Textures should always contain mipmaps (see http://en.wikipedia.org/wiki/Mipmap)~~
since they can get generated.

**Comment by MartinMuzatko** [comment]
We should make this part of the [data repository](https://github.com/inexor-game/data) readme. At least put a pointer there to this issue or copy this to the wiki

**Comment by Croydon** [comment]
See https://github.com/inexor-game/code/wiki/Inclusion-Standard
I will close this issue now, but further feedback can still be given here.
