### ISSUE TITLE
Update CEF to a more recent version

### ISSUE THREAD

**Issue by DarkDeepBlue** [inexor-game/code#271]
CEF should be updated to a more recent version, for example branch 2526.

CEF should be updated anyway to provide a proper ABI for GCC 5.3. The changes to the API are not really heavy and the current code can be changed easily.

The problem ist that the current stable branch is still not compatible with GCC 5.3, so maybe we should compile the whole CEF library using GCC 5.3.

**Comment by bebehei** [comment]
BTW: I'm currently working on my server to setup a complete Jenkins installation. If someone could contribute a script to compile libcef, this would be great.

**Comment by DarkDeepBlue** [comment]
Firstly, the compilation of libcef is pretty resource consuming. I’m not sure how powerful your server is, but that is something you have to keep in mind. Also, the compilation of libcef should happen for all platforms we are interested in.

Secondly, why exactly do you need a script? The thing one have to do is to get all the dependencies and compile the source. Now, I’m not familiar with all the details of that particular library, but the general question is what would be the benefit of some sort of script here.

**Comment by bebehei** [comment]
There is enough power to build cef in a reasonable time.

If you've got a script, this would give me some hints, how you use the combination of cef and inexor. That's all. :smile:

**Comment by Fohlen** [comment]
There's an automatic build flow for libCEF provided by Google which can be found here 
https://bitbucket.org/chromiumembedded/cef/wiki/BranchesAndBuilding.md#markdown-header-automated-method

**Comment by Fohlen** [comment]
Considering the branch to choose we should follow Chromiums release schedule, 2357 is the latest stable release branch AFAIK. Concerning the resources you need to think of an architecture that can share the working directory as well as the build cache since that's about 16 gigabyte and you really don't want to download that independantly for every container

**Comment by DarkDeepBlue** [comment]
On Archlinux Chromium actually uses branch 2526 since around 2015-12-09. Hence, I think that branch 2526 of CEF is also stable.

**Comment by bebehei** [comment]
One month later: I had been able to create a [libcef-git PKGBUILD](https://github.com/bebehei/libcef-git). This is currently based on branch 2526. I'm testing the PKGBUILD right now. (in terms of dependencies. This takes time and requires rebuilding the full PKGBUILD for every change.) Details about a repo will follow, too.

If you want too testbuild inexor against the current libcefbranch, you can [download my package](https://dl.b3be.de/libcef-git-2526.1366.8617e7c-1-x86_64.pkg.tar.xz). The package contains /usr/lib/libcef.so (which is obviously the library :smile: ) and /usr/share/libcef-full-list (which contains the full export built by ninja.). Yes, the package-function need some fixes, too!

**Comment by aschaeffer** [comment]
Done in 669bc51 in branch karo+fohlen+hanack/fix_cef
