### ISSUE TITLE
Offering bouncer access

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#273]
I am willed to share my bouncer based on [ZNC](http://znc.in) for everyone who has serious intentions to contribute to Inexor. If anyone, maybe @DarkDeepBlue or @bebehei sees himself in need of, please let me know.

**Comment by DarkDeepBlue** [comment]
I recently looked into the issue myself and would appreciate it if you would share your bouncer. :)

**Comment by bebehei** [comment]
@Fohlen If you could share a small howto, this would be perfect. If this tutorial also treats me like a noob and explains everything this would be awesome!

**Comment by DarkDeepBlue** [comment]
@bebehei

# ZNC

1. Open the URL that was provided by @Fohlen and log in with your user name and password.
2. In the ZNC UI go to »Your Settings«, change your password and set up whatever you like
3. Unter »Networks« you can add a new network. Click on »Add« to do so.
4. In the network settings, set ›BindHost‹ to '0.0.0.0'
5. In the network settings, under ›Servers of this IRC Network‹ add the network we are in
6. In the network settings, under »Channels«, add the cannel we are in
7. Perform additional changes as you like
8. Click on »Save and return« at the bottom of the page

# Pidgin

As far as I know you use pidgin, so you should follow the instrcutions [here](http://wiki.znc.in/Pidgin) to connect Pidgin with the ZNC server.

If something is not clear we can discuss on IRC or Mumble.

**Comment by bebehei** [comment]
Ok: What are the actual connection credentials for ZNC?
Server: `(znc|irc).darkkeepers.dk`
Port: `6697` or `64738`?
SSL: `true` or `false`?
Username: <my username> -> `bebehei`
Password: <my password set in znc>

I'm hitting timeouts with any configuration tested!
