### ISSUE TITLE
Pressing the button to open the chat-console also prints the key in the chat-console (saycommand)

### ISSUE THREAD

**Issue by obstriegel** [inexor-game/code#279]
How to reproduce:

- Launch inexor (default configuration)
- hit t to open the chat-console

The chat-console opens and a "t" appears in the chat-console which should not be there.
This happens only once. After you opened the chat one time it works fine.

OS: Ubuntu 14.04.3
master branch rev 7650f294c252b97eafbcab76460d8aadd0a3385d

**Comment by Croydon** [comment]
Related to #177

**Comment by Fohlen** [comment]
No it's not.. This error has to be fixed separately. CEF double input has already been fixed in the seperate process mode.
