### ISSUE TITLE
Upgrade protobuf definitions

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#283]
Using Ubuntu 15.10 and upstream ships along protobuf-compiler 2.6.1
This is problematic since the protobuf API has been changed specifically concerning our service definition. Release notes are listed below

* [Release notes v2.6.0](https://github.com/google/protobuf/releases/tag/v2.6.0)
* [**Release notes v2.6.1**](https://github.com/google/protobuf/releases/tag/v2.6.1)

Generating with protoc 2.6.1 will create the following code
*(interesting passage picked)*
```cpp
void Cubescript::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  code_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}
```
As mentioned in the 2.6.1 release notes this can bring memory leaks, and has therefore been sanitized/deprecated.
The linker will fail with the following message
```bash
../rpc/libmodule_rpc.a(inexor_service.pb.cc.o): In Funktion `google::protobuf::internal::GetEmptyStringAlreadyInited()':
/usr/include/google/protobuf/generated_message_util.h:80: Nicht definierter Verweis auf `google::protobuf::internal::empty_string_'
/usr/include/google/protobuf/generated_message_util.h:81: Nicht definierter Verweis auf `google::protobuf::internal::empty_string_'
../rpc/libmodule_rpc.a(inexor_service.pb.cc.o):(.rodata+0x230): Nicht definierter Verweis auf `google::protobuf::Message::GetTypeName() const'
../rpc/libmodule_rpc.a(inexor_service.pb.cc.o):(.rodata+0x250): Nicht definierter Verweis auf `google::protobuf::Message::InitializationErrorString() const'
../rpc/libmodule_rpc.a(inexor_service.pb.cc.o):(.rodata+0x2f0): Nicht definierter Verweis auf `google::protobuf::Message::GetTypeName() const'
../rpc/libmodule_rpc.a(inexor_service.pb.cc.o):(.rodata+0x310): Nicht definierter Verweis auf `google::protobuf::Message::InitializationErrorString() const'
../rpc/libmodule_rpc.a(inexor_service.pb.cc.o):(.rodata+0x3c8): Nicht definierter Verweis auf `google::protobuf::Message::GetTypeName() const'
../rpc/libmodule_rpc.a(inexor_service.pb.cc.o):(.rodata+0x3e8): Nicht definierter Verweis auf `google::protobuf::Message::InitializationErrorString() const'
../rpc/libmodule_rpc.a(MCRpcServer.cpp.o): In Funktion `inexor::rpc::MCRpcServer::ProcessOneCall()':
/home/fohlen/workspace/inexor/code/inexor/rpc/MCRpcServer.cpp:81: Nicht definierter Verweis auf `google::protobuf::MessageLite::SerializeAsString() const'
```
*(I excuse myself for German linking errors, but the problem gets pretty obvious)*

Subsequently, this breaks the linking, making ```SerializeAsString()``` in ```inexor/rpc/MCPRpcServer.cpp``` at line 81 unavailable.

### What to do now?
We can either

1 Include self-compiled < 2.6 protobuf headers
2 Fix the problem within the ```inexor_service.proto```

Unfortunately I don't have the knowledge to do the 2nd thing.

**Comment by koraa** [comment]
second

**Comment by koraa** [comment]
I But that doesn't sound like a problem with the protobuf file. That sounds like a different of protobuf where used when compiling the .proto and when linking the protobuf lib

**Comment by Croydon** [comment]
@Fohlen Please tag "invalid" when the issue is..well, invalid. :)
