### ISSUE TITLE
Use bower for our website as well

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#295]
Since we ship [bower](http://bower.io/) with the current Node.JS already, why shouldn't we make use of it's awesomeness for our website as well?

**Comment by MartinMuzatko** [comment]
Why use sometimes npm and sometimes bower? Why not just npm?

**Comment by Croydon** [comment]
Everything we are fetching right now with Bower is available via npm as well, so it is a good question.

**Comment by Fohlen** [comment]
Please dig into the following discussion,
http://stackoverflow.com/a/18652918
I hope it clarifies our use case a bit. Using solely npm and browserify would mean deciding for a compiler strategy as well as providing files at runtime via a middleware. With bower we can use static files and RequireJS logic, which we'd use anyway with bootstrap in mind.

**Comment by MartinMuzatko** [comment]
Depending on your build process, you could also deliver a distributable bundle (like I did here: https://github.com/MartinMuzatko/ui-prototype/tree/gh-pages/misan )

But I agree with using bower.

**Comment by Croydon** [comment]
The arguments for npm AND bower dual seems to be outdated after npm >= 3 supports a flat dependency tree as well and use it as default whenever possible.

@Fohlen 
> Using solely npm and browserify would mean deciding for a compiler strategy as well as providing files at runtime via a middleware. 

I don't get this point. What compiler strategy? Providing files via runtime? 
Release packages should contain already all files IMO. But even if we load them dynamic it would be the same principle if we load them via npm or bower. And for developers it makes no difference as well, npm and bower are getting this dependencies on call.

Is the only last issue different saving locations?

**Comment by Croydon** [comment]
We planning to replace the website. The new one will use NPM. See #365
