### ISSUE TITLE
Can't copy file  - path too long

### ISSUE THREAD

**Issue by MartinMuzatko** [inexor-game/code#297]
Hello there!
I jus tried to install this beautiful game, when I got this error:

![image](https://cloud.githubusercontent.com/assets/2950505/14722746/539e79b0-080d-11e6-9b7a-57a185bcbc63.png)

Maybe my HDD is too full (30gb left) but that shouldn't be the issue.

Ideas?

**Comment by a-teammate** [comment]
thats probably bc of the npm (node package manager)..
maybe we could upgrade to v3 to solve that, see https://docs.npmjs.com/how-npm-works/npm3

**Comment by bebehei** [comment]
[Windows has got a maximum path length of about 256 characters.](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#maxpath)

Try installing inexor in a higher directory.

**Comment by Croydon** [comment]
@a-teammate Sounds good to me, I had the same problem over and over again.

**Comment by Croydon** [comment]
While at it we should update our portable node.js version as well.

**Comment by Croydon** [comment]
Fixed by 84d8896cd7a2b83de5e75ec0d47c44f83a6809b2 + 1c9a0302fd619321ad40032cd98499ae5dad8747 + 2702b8a8a12285d5bed785de6eafa7d1febc01f0 + 3714288df203baa82d9f4f557e9a53a6565b5d16
