### ISSUE TITLE
Document Toolset considerations CEF/Electron

### ISSUE THREAD

**Issue by MartinMuzatko** [inexor-game/code#298]
Hello there!

I just started yesterday with contributing to this project.
I'd love to have a few more informations on the toolset decisions. Especially CEF.

A more modern approach would be [Electron](http://electron.atom.io/) ( [Article about CEF vs Electron](https://openfin.co/2015/12/07/why-were-moving-to-electron/)  )

While it is way too late to reconsider using CEF or Electron, I'd love to know which benefits you see.

Thanks a lot in advance.

**Comment by a-teammate** [comment]
Hm, if i remember correctly, we even had some kind of prototype for Electrons predecessor atom shell ( https://github.com/inexor-game-obsolete/inexor-atom-ui )
however i think its i think its been dropped bc we havent had enough control about the lib to integrate it correctly, maybe that point is gone now, dunno. (there might be a more detailed description in our historical pads)
