### ISSUE TITLE
UI Mockups for Menus/HUD

### ISSUE THREAD

**Issue by MartinMuzatko** [inexor-game/code#303]
Currently working on UI Mockups/Sketch Layouts.

Looking for a main menu layout that is flexible enough to extend + giving a great overview.
I wanted to open up an issue on https://github.com/inexor-game/ui-prototype, where this issue might fit. They are only open for PRs though.

# Main Menu

## Steam Like (Library) 

![image](https://cloud.githubusercontent.com/assets/2950505/14770932/51d3fc7e-0a7c-11e6-9d0c-a248640423a2.png)

Comparable to [Steam](http://static.giantbomb.com/uploads/original/2/29874/2438982-like+this.jpg)

**Comment by Croydon** [comment]
I guess it is better if you are creating a PR in the UI prototype repo instead posting them all in an issue.

**Comment by MartinMuzatko** [comment]
I'm collecting UI Sketches/Mockups. I'm not sure if merging images would be a good idea for the UI prototype repo. Thoughts?

**Comment by Fohlen** [comment]
I love the drafted UI Mockup. Have you had the chance to add something to the UI repo? Can you test that with CEF? I'd bet i'd make a pretty awesome screen shot embedded in CEF

**Comment by MartinMuzatko** [comment]
thanks @Fohlen. As already explained, the https://github.com/inexor-game/ui-prototype does not support Issues. I'd open the discussion there then if I could. So this issue should be the base of a discussion on what to improve and do other proposals, before coding/implementing them :)

**Comment by Croydon** [comment]
@MartinMuzatko We have decided to only have one issue tracker for everything.

**Comment by Croydon** [comment]
We already have an issue for a better hud: #98

**Comment by MartinMuzatko** [comment]
I'll move it there then, thank you :)
