### ISSUE TITLE
Services: Team E-Mail Server

### ISSUE THREAD

**Issue by Croydon** [inexor-game/code#315]
We want to setup again an email server for Inexor team members.
If somebody has experience with this we would like to hear from you. Every help is appreciated. :smile:

**Comment by bebehei** [comment]
Suggesting [uberspace](https://uberspace.de/): They've got pretty decent mailhosting. Like you know them, everything configurable via shell. Fast IMAP server (faster than mailbox.org). Big Pro: You don't have to host your own mailserver.

Only downside: They do not support greylisting as their MTA does not support it. But they've got other very good alternatives (DSPAM).

I had to migrate my mailbox from my old hoster 3 weeks ago and I'm astonished of their mail service.

**Comment by Croydon** [comment]
https://mtmedia.org is so lovely and is sponsoring our email hosting.

@inexor-game/code-developers if anyone wants to have an @inexor.org email then please write @Fohlen in IRC.
