### ISSUE TITLE
overall package manager strategy/get rid of platform repo

### ISSUE THREAD

**Issue by a-teammate** [inexor-game/code#319]
## Currently the situation is:
- We use a CMake based build system
  - Dependency recognition is done in vendor/CMakeLists.txt (you "require_<packagename>" stuff)
- We have all our dependencies precompiled in the platform repo **for windows**
  - this includes even our own tools like our [gluecode generator](https://github.com/inexor-game/code/wiki/Overall-Architecture)
  - on windows C++-Libs (with STL dep) are incompatible between Debug/Release
    - makes in total 4 precompiled libs if you actually just need one {x64, x32} \* {Debug, Release}
- Just googletest doesn't allow precompiling and is in the `vendor` subfolder
  - this subfolder has external projects which need to be integrated into the build folder
- There are some **linux** prebuilts in the platform repo, too
  - libcef is not in any package manager
    - libcef furthermore requires some code beeing compiled with the project, we don't do that but precompile the `libcef_dll_wrapper` project as well
  - grpc and the underlying protobuf 3 are in alpha state (neither in package managers)
    - special care needed: youre versions need to be absolutely consistent ( protobuf's compiler libprotoc and our linked protobuf needs to be the exact same version as the protobuf with which grpc was built)
- some libs have shared libraries they need to be the same as the ones we compiled inexor with

**Maintenance is a problem: we have a lot of work upgrading our libs / adding new libs**

Recently package managers in c++ are a hot topic:
http://thetoeb.de/2015/02/04/heterogeneous-package-search-retrieval-cmake/
- [hunter](https://docs.hunter.sh/en/latest/) seems to be a promising one
  - eco system isnt as big as needed yet
    - we would need create even some common packages like SDL2
- [meson](https://github.com/mesonbuild/meson/wiki/Wrap%20dependency%20system%20manual) has a dependency managment solution! see #316 
- NuGet (windows only dev package manager) could provide some of the common libs
  - but its visual studio only

I'd say hunter is our best bet:
We will need to create hunter packages for:
- CEF
- SDL2 {_image, _mixer} (not fully in NuGet i think + linux package managers have it)
- enet (is in linux package managers but not in nuget)
- grpc / with protobuf (maybe could get nuget packages as well, but hunter will be a noop too)

another focus could lie on non-dev-specific package managers like the uprising windows package manger chocolatey  is still no crossplatform solution so not really an answer to our problems. However it could serve as replacement for our shipping of node.js, npm and git on windows.

**Comment by Croydon** [comment]
We use conan.io now. Solved by #351.
