### ISSUE TITLE
Optimizing CMake for Visual Studio

### ISSUE THREAD

**Issue by IAmNotHanni** [inexor-game/code#32]
Hey there.
Im not sure who configures these CMake files, but if you could change these settings it would be great:

1) set client_windows_32 as the default project to launch
2) Change the run time libraries to Multithreaded-Debug (not -DLL) so your builts can run on other PCs (/MD)
3) Change the floating point model to fast (/fp:fast)
4) Change the sub-system to windows, not Console (/SUBSYSTEM:WINDOWS)

(to be continued?)

**Comment by a-teammate** [comment]
Merged with #89 
Subfilters seem not to work, ill open another issue for that.
