### ISSUE TITLE
Use boost UUIDs instead of utils

### ISSUE THREAD

**Issue by IAmNotHanni** [inexor-game/code#326]
There is a problem in this branch: hanni/NewVisualScripting.
The following code:
utils/uuid.cpp, line 36:

`rc = clock_gettime(CLOCK_REALTIME, &tp);`

does not work on Win32. It seems to work on Linux based systems only!

![error message from Microsoft Visual Studio 2015](https://raw.githubusercontent.com/inexor-game/visualisations/91c8a51bf6c47d02cf742d985f4752f41f906ca9/tickets/error_clock_gettime_UUID_utils.jpg)

Instead of using util/uuid.hpp we should use [boost UUID](http://www.boost.org/doc/libs/1_61_0/libs/uuid/uuid.html)

**Comment by IAmNotHanni** [comment]
A possible fix is [this](http://en.cppreference.com/w/c/chrono/timespec_get)
Just replace **clock_gettime** with **timespec_get**:

`rc = timespec_get(&tp, TIME_UTC);`

**Comment by IAmNotHanni** [comment]
https://github.com/inexor-game/code/commit/6fbbf645aad1b9775d1467572ffcf6a6ee48d150 fixed it.

**Comment by Croydon** [comment]
Note: This issue was about a feature branch not master.
