### ISSUE TITLE
Add discord as plattform

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#343]
As we're already using it it would be lovingly to use discord to recover team communication..
Please also add stuff to the `README.md` so we can find the channels..

**Comment by Croydon** [comment]
I don't want to use a closed source application with a non-standard protocoll.

Furthermore I highly doubt that more devs have Discord instead IRC.
It is not only about the current team members, but also how we can recruit new ones.

**Comment by a-teammate** [comment]
I'd love if just some way of communication is going. It would be awesome if we'd be somehow reachable. where did our bouncers go?

I agree: we shouldn't use discord (and btw no one joined me on there, so "we are using it already" when none gave a crap is not really true). Its philosophy isn't appealing to me either.

IRC is bullshit in kinds of being reachable. People are never reachable in IRC. Plus point of IRC however is that everyone got it.

So we ideally need some sort of document-able chat like communication. E-Mails are too slow, Mumble isn't document-able,
But first thing is: Getting IRC back working.

**Well**
Discord is CEF based... We need some sort of communication and community system (personal messages, maybe contacts). Why not combine these things together and get some own chat messenger going? If we need bots we could still copy the API of either Discord or some alternative

**Comment by MartinMuzatko** [comment]
Did we give up on Teamspeak? I agree, a public (maybe even VOIP alternative to chat only) would be nice! I lost track of you guys in Teamspeak. Please update communication platforms as soon as possible :)

**Comment by Croydon** [comment]
@MartinMuzatko We never used Teamspeak. Some of us are regulary on Mumble. Have a look at https://github.com/inexor-game/code/wiki/Contact

**Comment by a-teammate** [comment]
He meant that @Croydon, he joined there from time to time.

@MartinMuzatko: Sure we still use it! If you want I can give you a summary of whats changed to get you back on board. :+1:  
(either on IRC or mumble today or tomorrow evening)

**Comment by a-teammate** [comment]
Close in favor of #352
