### ISSUE TITLE
Get the Pads back

### ISSUE THREAD

**Issue by a-teammate** [inexor-game/code#353]
In our server switch we lost a lot of work, namely the pads on pads.inexor.org

I heared we got a backup of those, so we should try to recover them.
But at least we need to get the backup-database somewhere public.

**Comment by Fohlen** [comment]
Since the original backups are considered lost (latest state), is it still needed to rely on our own pads?

**Comment by Croydon** [comment]
Backup restoring would still be very nice if possible.

For the future I suggest we use https://public.etherpad-mozilla.org and prefix all new pads with "inexor_"

**Comment by Croydon** [comment]
https://public.etherpad-mozilla.org/p/inexor I restored this list from our old piratepad all pad list

**Comment by aschaeffer** [comment]
You are my hero!

**Comment by Croydon** [comment]
@aschaeffer Don't thank me too soon, this list is very outdated :)

**Comment by a-teammate** [comment]
Guys check out Hackpad: https://hackpad.com/Conan-CEF-package-0pkeQtYefxs 
It looks nicer and has built-in markdown support.

However it seems to be unmaintained currently see https://github.com/dropbox/hackpad/issues/51
Maybe theres a good fork somewhere?
But on the upside you do not have to keep track of "oh which pad do you mean send me the link" i think, since thats saved in your account (plus you can 'follow' pads).

https://github.com/wentin/Hack-the-Hackpad would also be a possibility for the blog then

There is also https://www.nuclino.com/ but im not sure how to share pads publically and it does not seem to be open source. on the upside its hosted and looks nice on first glance

@Croydon 
which addons does it include?
https://sandstorm.io pimped their etherpad you can install through it: https://oasis.sandstorm.io/grain/bdZG26ZNRmLy2meohNiaY4

**Comment by Fohlen** [comment]
The wiki page(s) has been updated and this issue is closed because we decided on Mozilla and Hackmd.

**Comment by Croydon** [comment]
Could we please use https://hackmd.io/CYFhFYCYCMGYEYC0A2e9yJAYwKYENE4AOWRPHCABiz2AE5hLIg==?both# as a collection for all pads?


@Fohlen What about the backups?

**Comment by aschaeffer** [comment]
I've added the pads I know from my browser's history :-)

**Comment by Croydon** [comment]
I guess that means even old backups are gone.
