### ISSUE TITLE
Fix our website setup

### ISSUE THREAD

**Issue by Croydon** [inexor-game/code#355]
Every page except the landing page is broken.

I can confirm that it is NOT a PHP7 issue. I can run the code locally with PHP7 and Apache2. 
Maybe something with rerouting is broken? Wrong configuration of nginx?

**Comment by Fohlen** [comment]
Alright. I will dig into that ASAP.
Presumably it is due using a cache module that is no longer needed/supported in PHP7

Am 19.12.2016, 03:00, Croydon <notifications@github.com> schrieb:

Every page except the landing page is broken.

I can confirm that it is NOT a PHP7 issue. I can run the code locally with PHP7 and Apache2.
Maybe something with rerouting is broken? Wrong configuration von nginx?

**Comment by Fohlen** [comment]
It was caused by an empty data directory .. I suspect due to a failed cronjob..
Case closed.
