### ISSUE TITLE
Add landscape as a management tool for our server

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#357]
Since in the past there's been a whole lot of issues concerning the server and administration in my absence, I've suggested to use canonical landscape for management and monitoring.
I've been in touch with the Canonical team at London, and after a quick chat they've supervised me with https://landscape.canonical.com/set-up-on-prem
On-premises will be free for up to 10 servers..
I'll add this to our infrastructure soon and will add a launchpad/management group as well, so Inexor core members can easily monitor and manage the server via the interface.

**Comment by a-teammate** [comment]
Very nice!

**Comment by Fohlen** [comment]
We are using [linux-dash](https://github.com/afaqurk/linux-dash) at [stats.inexor.org](https://stats.inexor.org)
