### ISSUE TITLE
Separate Inexor Flex in it's own repository

### ISSUE THREAD

**Issue by aschaeffer** [inexor-game/code#360]
- [x] Move the Node-JS stuff in a new Github repository
- [x] Make Inexor Flex a submodule of Inexor Core
- [x] Make Inexor Flex starts Inexor Core (#354)

**Comment by aschaeffer** [comment]
Created repository https://github.com/inexor-game/flex

**Comment by Fohlen** [comment]
I'd like to "re-invent" the Node.JS counterpart since a lot of code wasn't initially built for the current situation.. can we have a talk about that anytime soon?

**Comment by Croydon** [comment]
> Make Inexor Kernel a submodule of Inexor Flex

I don't think that this is a good idea. Code is in every aspect our main repository, our main point on GitHub and the repository everyone checked out. We would split, break or interrupt all of that. 

I get your point that flex will start core, but that doesn't prevent flex as a submodule in core, right?

**Comment by a-teammate** [comment]
True, both can work 

Btw is it Kernel or Core? Just to be consistent

**Comment by aschaeffer** [comment]
Good point. No it doesn't prevent flex as a submodule in core, so we re-reverse it :-)

**Comment by a-teammate** [comment]
Maybe we should also make 'flex' an own issue tag (@Croydon)

**Comment by Croydon** [comment]
@a-teammate We could do that ofc, on the other hand flex is a critical, mandatory part of the engine, so maybe just use that label?

**Comment by a-teammate** [comment]
Or maybe add the language as a label
e.g. `lang:js`, `lang:cpp` `lang:cmake` `lang:python`
so people could look for issues in the lang they speak.

but we can also leave it out, maybe its too much label spam (since some issues have different langs)
