### ISSUE TITLE
Replace the current website with inexor-game/site

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#365]
I've built a new website using [vue.js ](https://vuejs.org/) as a single page application.
I'd like it to replace the current blog site because

- it ships with [Bootstrap 4](https://v4-alpha.getbootstrap.com/), no more custom HTML framework
- it's entirely in the browser, get rid of the server and cronjobs
- since [babel](https://babeljs.io/) is used, it runs consistently in all major browsers and even IE8
- it uses the [Github API](https://developer.github.com/v3/), making it capable of in-depth blog search

Stll the following is to-do for the repository:

- [x] fix the bootstrap layout for blog and blog entries
- [x] enhance the current blog page to display more entries
- [x] fix a bug where the entry list constantly shrinks when using the search (should be notably easy)
- [x] ~~sometimes in the future replace [vue-resource](https://github.com/pagekit/vue-resource) with [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API), and a [polyfill](https://github.com/github/fetch)~~

**Comment by Croydon** [comment]
> it's entirely in the browser, get rid of the server and cronjobs

Do I understand it correctly, that at the point of time, where we want to have dynamic features to interact with users on our website, we will need a rewrite again? 
Or of course some third party integration, but this may be contradictionary for the long term goal of having players chats/contacts and an own eco system in general etc.

For example what is about #267? 
We should find common ground about these things before we have yet another complete rewrite of our website (remember the many versions we already had?)

**Comment by Fohlen** [comment]
No we don't. We add an API in the back (for instance with Node.js) and make requests to that. Same website, still no dependence on server-side rendering.

**Comment by Croydon** [comment]
Alright. @Fohlen How do you want to implement the blog in general? Can the current structure stay or is the plan to replace it completely?

**Comment by Croydon** [comment]
@Fohlen please don't introduce again external resources, keep it local

**Comment by Fohlen** [comment]
The structure stays exactly as it is..
Since the external CSS and resources are verified using [subresource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) in my opinion there is no problem with including them via a CDN.
Furthermore it brings benefits for us:

- the load is distributed among multiple servers
- due to the async calls of CDN the site page is notably boosted
- the toolchain required to build/update and pull in the latest version of assets is immense to including them via a CDN

**Comment by Croydon** [comment]
* we still need some kind of cronjob; the website should refresh after some short time when somebody pushed to git (or the next point)

* to further reduce our need for resources, we can setup an extremly simple Travis hook, which executes only `npm install && npm run build` and pushes then everything to some kind of inexor-game/site-binary repository. When I understand the nature of your rewrite correctly, we can then simply use GitHub Pages with our inexor.org domain (more uptime, more resources for other stuff!)
 * if we add some dynamic user interaction stuff in the feature, we can use a subdomain and it should be fine

* so if you care about the load see last point. In general I like it when the production site is self-contained. speed advantages with CDNs are not always given since more DNS lookups have to happen. Privacy+security advantages may not be that big when hashes used, but still there.

> the toolchain required to build/update and pull in the latest version of assets is immense compared to including them via a CDN

We can use for Bootstrap, Font Awesome and Bootstrap NPM as well. Updates should be finished with changing two times a version number and `npm update`

**Comment by Fohlen** [comment]
- true, but this does involve quiet less logic since no merge conflicts can happen due to the multiple configurations and the submodule
- the problem is not only keeping them up-to-date, but as well the boilerpalette code needed to get it working with bootstrap
- no, we can't host it at Github Pages, since that is not possible with SSL
- that is also not true, since the boilerpalette produced by webpack is usually quiet a bummer, splitting up the css produces bummers as well
- I guess no setup that we can provide comes nearly closely the used CDN services

**Comment by Fohlen** [comment]
Once @aschaeffer helped me auditing the styles, the site should be ready to be used.
Pagination can be added, but is quiet an effort compared to what can be done in the same time, and since we only have 10 blog posts, it'll be better to add this as a separate issue.

**Comment by Fohlen** [comment]
The following is on my/our to-do list for the new website:

- [ ] adjust and fix the styles for blog, disqus, the main page, the team page, @IAmNotHanni 
- [ ] add a "Ingame/News" tab using @inexor-game/aggregator
- [ ] add a "Ingame/Media" tab that contains the youtube videos
- [ ] add a link to the botbot.me logs
- [ ] add a youtube forward on inexor.org/yt
- [ ] use `history` mode, so we don't break the links
- [ ] add a download button and link for the nightlies @aschaeffer 
- [ ] add a link to the simple build instructions #381

**Comment by Fohlen** [comment]
Notably, the `aggregator` is ready to use. Only a `uWSGI` file is needed to get it started.

**Comment by terencode** [comment]
I'm currently working on fixing the layer for Blog and People section.

**Comment by Fohlen** [comment]
Since @terencode did a major bug fixing and the layout is now clean and nice, and the website works, can we ditch the old site?

**Comment by Fohlen** [comment]
I will add the content aggregation to another ticket.

**Comment by Croydon** [comment]
Is there anything left which the old website supported/had but the new one doesn't?

**Comment by a-teammate** [comment]
> Fohlen[22:53]: Croydon (Nooby): no
