### ISSUE TITLE
Evaluate server needs for this year

### ISSUE THREAD

**Issue by Fohlen** [inexor-game/code#370]
Since the current server expires on February the 2nd, I have some thought to go:

- my private use is currently only limited to `darkkeepers.dk` and affiliated services
- everything else drives Inexor
- since the [nooblounge will be migrating to new servers](http://nooblounge.net/index.php?site=news_comments&newsID=344), we might think about migrating servers for capacity as well as for costs

As for the downtimes, the reason is probably capacity issues with disk IO caused by `MongoDB/RocketChat`.
The current server is hosted at NetCup, pretty much the same as the [RS 1000 G7 SE](https://www.netcup.de/vserver/#features), the HDD flavor.

When evaluating the infrastructure, please keep the following in mind

- we need a central service to distribute SSL certificates (for Let's encrypt)
- we need a low-performance host for website and FTP
  - both can be on a cheap HDD storage
- we need high performance host for Rocket.Chat and Jenkins
  - both are preferred to use a SSD
  - specifically the Jenkins machine does need a lot of developer packages, it is best suit to separate it from the infrastructure

Since the infrastructure varies between different services and different load scales (e.g: during build time), the infrastructure should be capable of handling extremly high performance, but for most of the time is expected to run at very low usage.
Because of that nature cloud hosting could both be cheaper and more efficient for us to use..

**Comment by Fohlen** [comment]
Since I've got no feedback so far, I will be migrating some of the services to uberspace.
That means:

- the main site will run on uberspace more permanently
- since it doesn't take a lot of space, probably a new etherpad will also run there
- darkkeepers.dk will also run there (including game servers)
- the mail servers are running there (relieving mtmedia)
- as cloud.darkkeepers.dk and the ftp server are very storage intensive, I am looking forward to provide the means with a [S3 storage](https://aws.amazon.com/de/s3/pricing/), which is really cheap for long term storage
- we might be using [CodePipeLine](https://aws.amazon.com/de/codepipeline/?sc_channel=PS&sc_campaign=acquisition_DE&sc_publisher=google&sc_medium=english_codepipeline_b&sc_content=codepipeline_e&sc_detail=codepipeline&sc_category=code_pipeline&sc_segment=159755356511&sc_matchtype=e&sc_country=DE&s_kwcid=AL!4422!3!159755356511!e!!g!!codepipeline&ef_id=WDB4dwAAADHvLaIm:20170116152852:s) as an alternative to Jenkins, or alternatively run a seperate EC2 instance for Rocket.Chat and Jenkins

What does this mean:

- I have already issued a DNS update to use uberspace and the website already runs there
- It'll take some time to figure out Let's Encrypt
- You can contact me for mail adresses, as you need them
- Optionally, a Mumble server may be hosted there as well .. if we need that!

**Comment by aschaeffer** [comment]
please wait & mumble...

**Comment by Croydon** [comment]
We never decided to use Rocket.Chat, please post your opinion here: #352.

**Comment by Croydon** [comment]
Why did we just migrate our emails to mtmedia to not have to manage that anymore on our own, just to migrate it again now?

**Comment by Croydon** [comment]
> Optionally, a Mumble server may be hosted there as well .. if we need that!

Again, see #352. Seems like we don't need Mumble anymore.

> Since I've got no feedback so far

Please be more patient then ~20hours.

**Comment by Fohlen** [comment]
> We never decided to use Rocket.Chat
Just because we never decided something does not mean we won't give it a try..

> Why did we just migrate our emails to mtmedia to not have to manage that anymore on our own, just to migrate it again now?
If you've checked your email inbox quiet recently, mtmedia has already troubles with finances. I think they are better of if we don't use their resources for something we can get cheap and stable somewhere else.

> Please be more patient then ~20hours.

I've been announcing this quiet a couple of time via IRC and Rocket.Chat

> This would mean another thing to maintain. I guess we are better off when we use existing public pads and download important pads sometimes. It's sometimes possible to create a team. So let's create an Inexor team somewhere and let's go?

That is true. But it also grants us more privacy and freedom what happens with the Inexor ideas.
Furthermore, as far as I can see, I do not expect any changes in the setup for a decent amount of time.

**Comment by Fohlen** [comment]
I'd just wanted to note down as well that TitanPad, that we've been using quiet exhaustingly, [is closing down soon](http://blog.titanpad.com/2016/11/shutting-down-titanpad_12.html), which might be additional reason to host a pad ourselves.

**Comment by Croydon** [comment]
@Fohlen I can't remember ever seeing a TitanPad, did you use that while on Mumble?

> I've been announcing this quiet a couple of times without much of reactions via IRC and Rocket.Chat, during the past year

You reminded us that we need to pay for the server again, not a detailed action plan what we could change.

**Comment by Fohlen** [comment]
The website is now on uberspace running fine so far. Closing this for now.

**Comment by Croydon** [comment]
@Fohlen Website doesn't seem to update.

**Comment by aschaeffer** [comment]
The NoobLounge will provide resources for Jenkins and Nightlies :-)
