### ISSUE TITLE
Replace all include guards with pragma once

### ISSUE THREAD

**Issue by a-teammate** [inexor-game/code#389]
Include guards are error-prone (e.g. if you use the same guard twice) and furthermore are more to type and its said they are even less performant sometimes.

However `#pragma once` are supported for almost 5 years by the big compilers.

https://en.wikipedia.org/wiki/Pragma_once

Task: Replace in every header file include guards with pragma once

**Comment by aschaeffer** [comment]
Actually that's a nice good first bug.

**Comment by fallinbryan** [comment]
I would like to get involved in the open source community.  May I take on this issue?

**Comment by a-teammate** [comment]
Sure go ahead :)
