### ISSUE TITLE
Appveyor build time exeeds

### ISSUE THREAD

**Issue by a-teammate** [inexor-game/code#394]
Currently there are **no** packages for visual studio at all in the inexorgame conan repos.
There are two options to fix this:
1) fast: revert #379 until there are packages for vs for the inexorgame conan packages
2) set up appveyor and Travis correctly for all dependencies for the inexorgame ones

Reason: every appveyor build fails since the build time exceeds (this is also a cumbersome experience for anyone building inexor for the first time on a windows machine)

**Comment by a-teammate** [comment]
Thank you @Croydon! Very cool :)

Note: any modifications of dependencies.py trigger a build of all "inexorgame" dependencies which get pushed to conan.io afterwards.

**Comment by Croydon** [comment]
Clarification: The automatic building of all deps isn't merged yet.
