### ISSUE TITLE
Inexor Flex Profiles

### ISSUE THREAD

**Issue by aschaeffer** [inexor-game/code#397]
Profiles greatly improves the startup procedure of Inexor Flex, makes the Inexor Shell able to control other instances of Inexor Flex and makes the development process more effective.

### Goals

* Run multiple instances of Inexor Flex on a system
    * e.g. Testing of tree synchronization (e.g. server list sync)
    * e.g. Running a separate Inexor Flex instance for each clans/communities on the same VM
* Use specialized profiles for special purposes
    * e.g. logging enabled, log level=debug (dev profile)
    * e.g. logging disabled, log level=warn (production profile)
* Connect to remote instances of Inexor Flex
* Easier to develop, debug and test
* Helps to bundle specific packages of Inexor (Game Client Distribution, Game Server Distribution)

### User Stories

- [x] As a user I want to run the Inexor Game Client `npm start`
- [x] As a server administrator I want to control my (remote) game servers with the Inexor Shell (see note 1)
- [x] As a server owner I want to run multiple instances of Inexor Flex on the same VM in order to isolate the servers of hosted clans/communities
- [x] As a developer I want to start Inexor Flex in development mode easily `npm run dev`
- [x] As a developer I want to start multiple instances of Inexor Flex at the same time
- [x] As a distributor I want to provide a reasonable set of profiles for my bundle

### Inexor Tree

- [x] The name of the default profile (this is the profile to use if Inexor Flex is started without a profile)
  * `/flex/profiles/default` = "client"
- [x] The name of the current profile
  * `/flex/profiles/current` = "devenv"
- [x] The names of all profiles
  * `/flex/profiles/{profilename}`
- [x] The configuration of a profile has it's own folder:
  * `{configFolder}/inexor/{profilename}`
        
#### Logging

| Profile     | Log level | Log to console | Log to file |
| - | - | - | - |
| `client`    | warn | false | false |
| `server`  | warn | false | true |
| `devenv` | debug |  true | false |

#### Instances

| Profile     | Server | Client |
| - | - | - |
| `client`    | yes, no autostart | yes, autostart |
| `server`  | yes, autostart | no |
| `devenv` | yes, no autostart | yes, no autostart |

#### Config files

- [x] client
  * name: Default production client
  * description: Production-ready client and optional local server
  * hostname: localhost
  * port: 31416
  * logging (logging.toml):
    * log level: warn
    * log to console: false
    * log to file: false
  * instances (instances.toml):
    * 31414
      * type: server
      * name: Default production server
      * autostart: false
      * autorestart: false
      * enet_port: 31415
    * 31417
      * type: client
      * name: Default production client
      * autostart: true
      * autorestart: true
- [x] server
  * name: Default production server
  * description: Production ready server
  * hostname: localhost
  * port: 31416
  * logging (logging.toml):
    * log level: warn
    * log to console: false
    * log to file: true
  * instances (instances.toml):
    * 31414
      * type: server
      * name: Default production server
      * autostart: true
      * autorestart: true
      * enet_port: 31415
- [x] devenv ()
  * name: Development environment
  * description: Local development environment
  * hostname: localhost
  * port: 31416
  * logging (logging.toml):
    * log level: debug
    * log to console: true
    * log to file: false
  * instances (instances.toml):
    * 31414
      * type: server
      * name: Default development server
      * autostart: false
      * autorestart: false
      * enet_port: 31415
    * 31417
      * type: server
      * name: Default development client
      * autostart: false
      * autorestart: false

### Inexor Shell

- [x] The prompt shows the currently selected profile name and the hostname and port from the current profile:
  * `profilename@hostname:port > _`
- [x] By default, Inexor Shell uses the default profile
  * Normally the default profile is the local instance of Inexor Flex (localhost:31416)
  * e.g. `default@localhost:31416 > _`
- [x] A profile can be a remote instance of Inexor Flex
  * e.g. profile named `remote1`
    * hostname = remotehostname.com
    * port = 31416
  * e.g. `remote1@remotehostname.com:31416 > _`
- [x] You can start an Inexor Shell with a profile argument
  * `inexor shell --profile=devenv`
  * `inexor shell --profile=remoteprofile`
- [x] Change the profile while using the Inexor Shell
  * `default@localhost:31416 > use devenv`
  * `devenv@localhost:31416 > use remote1`
  * `remote1@remotehostname.com:31416 > _`
- [x] New commands
  * `profile create <name> <hostname> <port>`
  * `profile remove <name>`
  * `profile switch <name>`
- [x] Inexor Tree Client
  * Hand over the current profile name as first argument of the commands
  * Add the profile name as first argument to every command
  * The profile contains the hostname and port to use and therefore we can communicate to any local or remote instance of Inexor Flex

### Inexor Flex

- [x] Command Line Argument "profile"
  * Start Inexor Flex with defaults
    * `npm start`
    * which is equivalent to `npm run inexor --profile default`
  * Start Inexor Flex with profile devenv
    * `npm run inexor --profile devenv`
    * which is equivalent to `node server/index.js --profile=devenv`
- [x] Loading from config files
  * `getConfigPath(profile, 'instances.toml')`
- [x] Startup Inexor Flex
  * Detect/load the list of profile names from filesystem (profiles.toml) and the name of the default profile
  * Set the current profile variable (from cmd line args)
  * Load current profile (port, hostname, ...)
  * Use `getConfigPath(currentProfile, 'instances.toml')` to start the Inexor Core instances
  * Loading logging configuration from config file ('logging.toml')

### Notice(s)

1. Security measures and cheating protection are not focus of this issue

**Comment by Croydon** [comment]
Just to clearify my confusion: A single Flex instance can run several Core instances. But without implementing all the stuff from this issues, all of the Core instances from a single Flex instance would be feed with the exact same configuration? 

I was under the impression that a single Flex instance can **already** manage several Core instances with different configs.

**Comment by aschaeffer** [comment]
It's about the configuration of Flex in the first place. You can have a completely other configuration for Flex in another profile, including another configuration of the instances. There is a config folder for each profile: `{configFolder}/inexor/{profilename}` where to put the configuration files. The combination of core instances and profiles makes it very powerful.

For example:

    $ ls /home/user/.config/inexor/default
    profile.toml
    instances.toml
    
    $ cat /home/user/.config/inexor/default/profile.toml
    port = 31416
    hostname = localhost
    loglevel = warning
    logtoconsole = false
    logtofile = true
    
    $ cat /home/user/.config/inexor/default/instances.toml
    [instances]
    [instances.31414]
    type = "server"
    name = "Default Inexor Server"
    description = "Badly Configurated Server Inc. proudly presents your first Inexor Server"
    autostart = false
    [instances.31417]
    type = "client"
    name = "Default Inexor Client"
    description = "The default Inexor Client"
    autostart = false
    
    $ ls /home/user/.config/inexor/devenv
    profile.toml
    instances.toml
    
    $ cat /home/user/.config/inexor/devenv/profile.toml
    port = 31416
    hostname = localhost
    loglevel = debug
    logtoconsole = true
    logtofile = false
    
    $ cat /home/user/.config/inexor/devenv/instances.toml
    [instances]
    [instances.31414]
    type = "server"
    name = "Dev Server"
    autostart = true
    [instances.31417]
    type = "client"
    name = "Dev Client"
    description = "The Dev Client"
    autostart = true

**Comment by a-teammate** [comment]
Just as a little note: the game client will also want to create a new local game server if it wants to play offline (the listenserver will be removed in one of the next PRs)

**Comment by aschaeffer** [comment]
Done.

If something is not working => reopen.
