### ISSUE TITLE
New Binary Structure

### ISSUE THREAD

**Issue by aschaeffer** [inexor-game/code#68]
The binaries will be deployed in a hierarchical structure, beginning with the operating system, then the CPU architecture.

## Hierarchical

* ROOT
  * OPERATING SYSTEM
     * ARCHITECTURE
       * CLIENT_BINARY
       * SERVER_BINARY
       * SHARED LIBRARIES

## Example:

* root
  * bin
    * linux
      * x86
        * inexor_client
        * inexor_server
        * libcef.so
        * chrome_sandbox
      * x86_64
        * inexor_client
        * inexor_server
        * libcef.so
        * chrome_sandbox
    * mac
      * x86
        * inexor_client
        * inexor_server
      * x86_64
        * inexor_client
        * inexor_server
    * win
      * win32
        * inexor_client
        * inexor_server
      * win64
        * inexor_client
        * inexor_server

**Comment by Fohlen** [comment]
Where would root/ be located at? Simply the game's location?

**Comment by koraa** [comment]
+1

**Comment by aschaeffer** [comment]
yes

**Comment by Fohlen** [comment]
+1

**Comment by Fohlen** [comment]
Please update this issue once the plattform renames are done. Maybe @killme can help rewriting the cmake-files n stuff.

**Comment by koraa** [comment]
I would also suggest that we use actual processor architectures instead of win32/win64.

**Comment by a-teammate** [comment]
Merged with cmake-update #89 
Some little adjustments will follow though

**Comment by koraa** [comment]
The file paths differ from the ones described here:

We use windows/{32,64} in the repo and windows/win{32,64} in this issue and in the platform_windows repo.
Which ones should we actually use?

**Comment by a-teammate** [comment]
lets go for win32/win64.

**Comment by koraa** [comment]
ok, will you please do the change?
