### ISSUE TITLE
Code Structure Suggestion: Namespaces and Modules

### ISSUE THREAD

**Issue by koraa** [inexor-game/code#70]
I suggest that we divide any new functionality into modules.

Such a module should have it's own namespace and it's own subdirectory, so for instance the module Gui would be in the namespace `inexor::gui` and would reside in `src/gui`.
These modules should provide a header with the name of the module (`src/gui/gui.h`) that servers as a convenience header to pull the entire functionality of that module.
Each of these modules should also provide a description of what the module does inside a readme file (`src/gui/readme.md`).

What do you think of these suggestions?

**Comment by Fohlen** [comment]
Sounds great so far. 
Please that namespaces could also be used to make our code backward-compatible (see, #1 ) by outsourcing existing modules to (eg) sauer::
Anyhow I don't see the point for very small modules (such as jSON-parser) who can ship everything and once and don't need a seperate folder.

**Comment by koraa** [comment]
Yup, outsourcing to sauer:: would be cool!

For very small modules I would suggest, that we either keep them in util/ or in the root source folder src/.
I would like to avoid storing modules inside engine/, fpsgame/ or shared/, because I consider those to contain all the legacy code.

**Comment by koraa** [comment]
Accepted and moved to the wiki.
