### ISSUE TITLE
Documentation Guidlines (And probably using Doxygen)

### ISSUE THREAD

**Issue by koraa** [inexor-game/code#71]
We should define guidelines for writing documentation so we keep a consistent style.

To be able to export to our documentation we should use a documentation generator. I suggest Doxygen for that task.

## What should be documented

In General the interface anything exposes must be documented,
in C++ code this would include the following:

* Classes/Structs should have a description header
* Functions, Methods and Macros should be commented in terms of
  + Arguments
  + Return Value
  + Side Effects (what state does this function alter)
  + Possible exceptions/Error Flags
  + Overloads
* Class/Global Variables should have a description
* Typedefs should also have a description
* Templates in general should have an extensive documentation
* Files should have a documentation, describing roughly what kind of stuff the file contains.
  + Files that are implicitly documented do not need a documentation, this includes
    - implementations of header files (`Fnord.cpp `is already commented in `Fnord.h`)
    - [Module][2] headers (`src/gui/gui.h`), because the module should already be documented (`src/gui/readme.md`)

## Comment Style

Comments that are not _Documentation_ (e.g. inside a method, sometimes implementation details) should always use C-Style online comments

    // This describes some implementation detail that is only
    // important for people touching this code, not for people
    // who only need to call this function we're inside.

For documentation we need to use the syntax of our generator. With Doxygen:
Doxygen uses many different syntaxes, the full documentation can be found [here][1].

For our case I think we should decide between a one-line style and a multiline-style:

    /// This is the short description with a one-line style documentation.
    ///
    /// This is the more detailed description.
    /// Which has multiple lines.
    ...

    /**
     * This is the short description with a multi-line style documentation.
     *
     * This is the more detailed description.
     * Which also has multiple lines.
     */
    ...

The one-line style has the advantage, that it requires less lines.
Multi-line style is better supported by some editors on the other hand.
Personally I prefer the multi-line style for no particular reason (probably because I used it before).

In any of those we need to use some semantic tags, e.g. when describing parameters.
Again there are multiple possible styles for that, but I suggest we use javadoc-style with `@`:

    /**
     * Safety dance.
     *
     * You can leave your friends if you want to,
     * you can leave them all behind.
     *
     * @param Something old.
     * @param Something borrowed.
     * @return Something new.
     * @see The elephant wedding.
     */
    void dance(...) {...}

[Modules][2] should have a documentation inside a readme.md file.

Any documentation and any comments in general may be formatted using markdown syntax.

## What needs doing

* We need a build setup that supports our generator.
* We need to make sure that this build setup supports readme.md files (see [this][3])
* We should integrate that into our CI and we should put that documentation online.
* If we feel like it we might create some custom styles for that documentation because doxygen is not very pretty.

What do you think of this?

# Please discuss :)

[1]: http://www.stack.nl/~dimitri/doxygen/helpers.html#doxfilt_js "Doxygen syntax documentation"
[2]: https://github.com/inexor-game/code/issues/70 "Suggestion for a code module structure"
[3]: https://stackoverflow.com/questions/13368350/use-the-readme-md-file-as-main-page-in-doxygen "Stackoverflow question on Doxygen and readme.md"

**Comment by Fohlen** [comment]
doxygen & doxygen-templates for code commenting. It is "the standard" in open-source, widely used and will handle a lot of the issues you mentioned above.
Bonus point: Doxygen can make documentations of functions/classes without any code comments.
Splitting documentation in several readme.md files is a usefull thing, but not necessary. When using doxygen propperly it will allow us to generate "sub-documents" for single modules.

**Comment by koraa** [comment]
Accepted and moved to the wiki.
