### ISSUE TITLE
Create a minimal, working demo

### ISSUE THREAD

**Issue by koraa** [inexor-game/code#75]
When a new user wants to give Inexor a try, they should get something to see!

For this purpose we should change the skin to something nice and we should provide a couple of simple maps.
These maps should be technical demos and they should look nice, to save us some time these maps should take little effort contentwise.

_(A detailed suggestion will follow. I am at wörk right now.)_

**Comment by IAmNotHanni** [comment]
Maybe we could script a beginner map with audio playbacks. I am inspired by Portal in this aspect: 
https://youtu.be/eFe3eKaKeF0?t=59s

This would be so awesome!

**Comment by Fohlen** [comment]
See @Coffeine-Edition
