### ISSUE TITLE
Use waffle.io as Kanboard

### ISSUE THREAD

**Issue by aschaeffer** [inexor-game/code#76]
Another possible Kanboard solution.

Pro's:
* integrated with github
* uses issues from github
* uses users from github

Cons:
* not self-hosted

Try it:
* https://waffle.io/inexor-game/code

See also:
* https://github.com/waffleio/waffle.io

**Comment by koraa** [comment]
I think it's OK to use that.

Waffle.io requires read access to the organizations, which they have to.
Waffle.io also demands access to email, which could be problematic but it probably is not. (Mine is public anyway)

**Comment by Fohlen** [comment]
I'll try that. But outsourcing isn't exactly the nicest thing to have..

**Comment by Croydon** [comment]
It's a nice thing :+1:
