### ISSUE TITLE
Use .win.cpp/.posix.cpp/… files for platform specific stuff.

### ISSUE THREAD

**Issue by koraa** [inexor-game/code#96]
Some features require platform specific implementations; until now we just used ifdefs for platform detection; this can be somewhat cumbersome, hence I suggest adding the possibility to save platform specific implementations of interfaces in their own files.

```
  puppies.cpp          # Used on every platform
  puppies.unix.cpp     # Used on real UNIX (OSX, Darwin, BSD, Solaris, Illumos, ...)
  puppies.posix.cpp    # Used on any posix systems (UNIX systems + linux)
  puppies.linux.cpp    # Used on linux
  puppies.osx.cpp      # Used on osx
  puppies.windows.cpp  # Used on windows
  ...
```

More special cases can be added (mingw, cygwin, darwin, freebsd, openbsd, android, win2000, ...) but using those might be more cumbersome than just using ifdefs.
Any platform specific implementation that applies should be compiled – on OSX for instance: .cpp, .unix.cpp, .posix.cpp, .osx.cpp

What do you think of this?

**Comment by aschaeffer** [comment]
Could be a little bit verbose, but better than make excessive use of preprocessor directives.

Another point is: you may not know what code is platform specific in beforehand.

**Comment by Fohlen** [comment]
Sounds like a great feature, although it seems like quiet a complex task.

**Comment by a-teammate** [comment]
thats more like a design decision.
in general it sounds good, though i don't see the need yet or a specific part of sauers codebase which really has so many platform specific stuff that it needs different files for that. (maybe some stream.cpp stuff, but even that is not slightly large enough imo).
Still good idea if we come to a point where we have to make such heavy platform-specific stuff, though i really hope we wont (since its pretty work-intense  )

**Comment by Croydon** [comment]
I guess we share the opinion that we don't need this right now. Can be closed?

**Comment by FaTony** [comment]
I suggest putting all platform specific code into a library, or, at least, a different directory. That way there will be a very clean separation of portable and non-portable stuff.

**Comment by Croydon** [comment]
Since there wasn't much feedback from team members I'm going to mark this WONTFIX now.

@Lyberta Imo here applies the same thing a_teammate said eailer: maybe we do this when we get to the point where we have heavy/much platform specific stuff.
